#ifndef _focs_hpp_
#define _focs_hpp_


namespace focs {

class AddSpecial;
class AddStarlanes;
class Conditional;
class CreateBuilding;
class CreateField;
class CreatePlanet;
class CreateShip;
class CreateSystem;
class Destroy;
class GenerateSitRepMessage;
class GiveEmpireTech;
class MoveInOrbit;
class MoveTo;
class MoveTowards;
class NoOp;
class RemoveSpecial;
class RemoveStarlanes;
class SetAggression;
class SetDestination;
class SetEmpireCapital;
class SetEmpireMeter;
class SetEmpireStockpile;
class SetEmpireTechProgress;
class SetMeter;
class SetOverlayTexture;
class SetOwner;
class SetPlanetSize;
class SetPlanetType;
class SetShipPartMeter;
class SetSpecies;
class SetSpeciesEmpireOpinion;
class SetSpeciesSpeciesOpinion;
class SetStarType;
class SetTexture;
class SetVisibility;
class Victory;
enum ComparisonType : int;
enum ContentType : int;
enum OpType : int;
enum ReferenceType : int;
enum SearchDomain : int;
enum SortingMethod : int;
enum StatisticType : int;
struct AccountingInfo;
struct Aggressive;
struct All;
struct And;
struct Armed;
struct Building;
struct CanAddStarlaneConnection;
struct CanColonize;
struct CanProduceShips;
struct Capital;
struct Chance;
struct CombatTarget;
struct Condition;
struct ContainedBy;
struct Contains;
struct CreatedOnTurn;
struct Described;
struct DesignHasHull;
struct DesignHasPart;
struct DesignHasPartClass;
struct Effect;
struct EffectCause;
struct EffectsGroup;
struct EmpireAffiliation;
struct EmpireHasAdoptedPolicy;
struct EmpireMeterValue;
struct EmpireStockpileValue;
struct Enqueued;
struct ExploredByEmpire;
struct FleetSupplyableByEmpire;
struct FocusType;
struct HasSpecial;
struct HasTag;
struct Homeworld;
struct InOrIsSystem;
struct Location;
struct MeterValue;
struct Monster;
struct NameLookup;
struct None;
struct Not;
struct Number;
struct NumberedShipDesign;
struct ObjectID;
struct OnPlanet;
struct Or;
struct OrderedAlternativesOf;
struct OrderedBombarded;
struct OwnerHasBuildingTypeAvailable;
struct OwnerHasShipDesignAvailable;
struct OwnerHasShipPartAvailable;
struct OwnerHasTech;
struct PlanetEnvironment;
struct PlanetSize;
struct PlanetType;
struct PredefinedShipDesign;
struct ProducedByEmpire;
struct ResourceSupplyConnectedByEmpire;
struct RootCandidate;
struct ScriptingCombatInfo;
struct ScriptingContext;
struct ShipPartMeterValue;
struct SortedNumberOf;
struct Source;
struct SourcedEffectsGroup;
struct Species;
struct StarType;
struct Stationary;
struct Target;
struct TargetsAndCause;
struct Turn;
struct Type;
struct ValueRefBase;
struct ValueTest;
struct VisibleToEmpire;
struct WithinDistance;
struct WithinStarlaneJumps;
template <typename From> struct StringCast;
template <typename From> struct UserStringLookup;
template <typename From, typename To> struct StaticCast;
template <typename Type> struct ComplexVariable;
template <typename Type> struct Constant;
template <typename Type> struct Operation;
template <typename Type> struct Statistic;
template <typename Type> struct ValueRef;
template <typename Type> struct Variable;

}


#endif
