#ifndef _Tokens_h_
#define _Tokens_h_

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/seq/for_each.hpp>

#define TOKEN_SEQ_1                             \
    (abs)                                       \
    (accountinglabel)                           \
    (activation)                                \
    (AddedBefore)                               \
    (AddedSince)                                \
    (AddSpecial)                                \
    (AddStarlanes)                              \
    (Adequate)                                  \
    (adoptioncost)                              \
    (affiliation)                               \
    (Age)                                       \
    (Aggressive)                                \
    (All)                                       \
    (allowed)                                   \
    (AllyOf)                                    \
    (And)                                       \
    (AnyEmpire)                                 \
    (Armed)                                     \
    (Armour)                                    \
    (ArrivedOnTurn)                             \
    (Article)                                   \
    (Application)                               \
    (Asteroids)                                 \
    (Attack)                                    \
    (Barren)                                    \
    (Basic)                                     \
    (BlackHole)                                 \
    (Blue)                                      \
    (Bombard)                                   \
    (Bomber)                                    \
    (buildcost)

#define TOKEN_SEQ_2                             \
    (Building)                                  \
    (BuildingTypesOwned)                        \
    (BuildingType)                              \
    (BuildingTypesProduced)                     \
    (BuildingTypesScrapped)                     \
    (buildtime)                                 \
    (CanAddStarlanesTo)                         \
    (CanColonize)                               \
    (CanProduceShips)                           \
    (CanSee)                                    \
    (capacity)                                  \
    (Capacity)                                  \
    (Capital)                                   \
    (Capture)                                   \
    (captureresult)                             \
    (category)                                  \
    (Category)                                  \
    (ceil)                                      \
    (class)                                     \
    (ClockwiseNextPlanetType)                   \
    (Colony)                                    \
    (colour)                                    \
    (CombatBout)                                \
    (combatTargets)                             \
    (condition)                                 \
    (Construction)                              \
    (consumption)                               \
    (ContainedBy)                               \
    (ContainerID)                               \
    (Contains)                                  \
    (Core)                                      \
    (cos)                                       \
    (Count)                                     \
    (CountUnique)                               \
    (CounterClockwiseNextPlanetType)            \
    (CreateBuilding)                            \
    (CreatedOnTurn)                             \
    (CreateField)                               \
    (CreatePlanet)                              \
    (CreateShip)                                \
    (CreateSystem)                              \
    (CreationTurn)                              \
    (CurrentContent)                            \
    (CurrentTurn)

#define TOKEN_SEQ_3                             \
    (damage)                                    \
    (Damage)                                    \
    (data)                                      \
    (default)                                   \
    (defaultfocus)                              \
    (DefaultFocus)                              \
    (Defense)                                   \
    (Described)                                 \
    (description)                               \
    (Desert)                                    \
    (design)                                    \
    (Design)                                    \
    (DesignHasHull)                             \
    (DesignHasPart)                             \
    (DesignHasPartClass)                        \
    (designid)                                  \
    (DesignID)                                  \
    (designname)                                \
    (destination)                               \
    (Destroy)                                   \
    (Detection)                                 \
    (DirectDistanceBetween)                     \
    (Disabled)                                  \
    (dislikes)                                  \
    (distance)                                  \
    (DistanceFromOriginalType)                  \
    (effects)                                   \
    (EffectsGroup)                              \
    (effectsgroups)                             \
    (else)                                      \
    (empire)                                    \
    (EmpireHasAdoptedPolicy)                    \
    (EmpireHasBuildingAvailable)                \
    (EmpireHasShipDesignAvailable)              \
    (EmpireHasShipPartAvailable)                \
    (EmpireHasTechResearched)                   \
    (EmpireMeter)                               \
    (EmpireMeterValue)                          \
    (EmpireObjectVisibility)                    \
    (EmpireShipsDestroyed)                      \
    (EmpireStockpile)                           \
    (Enabled)                                   \
    (endpoint)                                  \
    (EnemyOf)                                   \
    (Enqueued)                                  \
    (enqueuelocation)                           \
    (environment)                               \
    (environments)                              \
    (ETA)                                       \
    (ExploredByEmpire)                          \
    (exclusions)                                \
    (External)

#define TOKEN_SEQ_4                             \
    (Field)                                     \
    (FieldType)                                 \
    (Fighter)                                   \
    (FighterBay)                                \
    (FighterHangar)                             \
    (FighterWeapon)                             \
    (FinalDestinationID)                        \
    (Fleet)                                     \
    (FleetID)                                   \
    (FleetSupplyableByEmpire)                   \
    (floor)                                     \
    (foci)                                      \
    (focus)                                     \
    (Focus)                                     \
    (FocusType)                                 \
    (fuel)                                      \
    (Fuel)                                      \
    (Full)                                      \
    (GalaxyAge)                                 \
    (GalaxyMaxAIAggression)                     \
    (GalaxyMonsterFrequency)                    \
    (GalaxyNativeFrequency)                     \
    (GalaxyPlanetDensity)                       \
    (GalaxySeed)                                \
    (GalaxyShape)                               \
    (GalaxySize)                                \
    (GalaxySpecialFrequency)                    \
    (GalaxyStarlaneFrequency)                   \
    (gameplay_description)                      \
    (GameRule)                                  \
    (GasGiant)                                  \
    (General)

#define TOKEN_SEQ_5                             \
    (GenerateSitRepMessage)                     \
    (GiveEmpireTech)                            \
    (Good)                                      \
    (graphic)                                   \
    (HabitableSize)                             \
    (Happiness)                                 \
    (HasSpecial)                                \
    (HasSpecialCapacity)                        \
    (HasSpecialSinceTurn)                       \
    (HasTag)                                    \
    (high)                                      \
    (HighestCostEnqueuedTech)                   \
    (HighestCostResearchableTech)               \
    (HighestCostTransferrableTech)              \
    (HistogramMax)                              \
    (HistogramMin)                              \
    (HistogramSpread)                           \
    (Homeworld)                                 \
    (Hostile)                                   \
    (Huge)                                      \
    (hull)                                      \
    (Hull)                                      \
    (HullFuel)                                  \
    (HullSpeed)                                 \
    (HullStealth)                               \
    (HullStructure)                             \
    (Human)                                     \
    (icon)                                      \
    (id)                                        \
    (ID)                                        \
    (If)                                        \
    (Industry)                                  \
    (Inferno)                                   \
    (Influence)                                 \
    (InSystem)                                  \
    (Interceptor)                               \
    (Integer)                                   \
    (Internal)                                  \
    (Invisible)                                 \
    (Item)                                      \
    (jumps)                                     \
    (JumpsBetween)

#define TOKEN_SEQ_6                             \
    (label)                                     \
    (Large)                                     \
    (LastTurnActiveInBattle)                    \
    (LastTurnAttackedByShip)                    \
    (LastTurnBattleHere)                        \
    (LastTurnColonized)                         \
    (LastTurnConquered)                         \
    (LastTurnMoveOrdered)                       \
    (LastTurnResupplied)                        \
    (LaunchedFrom)                              \
    (LeastHappySpecies)                         \
    (likes)                                     \
    (LocalCandidate)                            \
    (location)                                  \
    (Location)                                  \
    (log)                                       \
    (Lookup)                                    \
    (low)                                       \
    (LowestCostEnqueuedTech)                    \
    (LowestCostResearchableTech)                \
    (LowestCostTransferrableTech)               \
    (max)                                       \
    (Max)                                       \
    (MaxCapacity)                               \
    (MaxDamage)                                 \
    (MaxDefense)                                \
    (MaxFuel)                                   \
    (MaximumNumberOf)                           \
    (MaxSecondaryStat)                          \
    (MaxShield)                                 \
    (MaxStockpile)                              \
    (MaxStructure)                              \
    (MaxSupply)                                 \
    (MaxTroops)                                 \
    (Mean)                                      \
    (Medium)                                    \
    (message)                                   \
    (meter)                                     \
    (min)                                       \
    (Min)                                       \
    (MinimumNumberOf)                           \
    (Missiles)

#define TOKEN_SEQ_7                             \
    (Mode)                                      \
    (model)                                     \
    (ModeNumberOf)                              \
    (Monster)                                   \
    (MonsterFleet)                              \
    (MostHappySpecies)                          \
    (MostPopulousSpecies)                       \
    (MostSpentEnqueuedTech)                     \
    (MostSpentResearchableTech)                 \
    (MostSpentTransferrableTech)                \
    (mountableSlotTypes)                        \
    (MoveInOrbit)                               \
    (MoveTo)                                    \
    (MoveTowards)                               \
    (name)                                      \
    (Name)                                      \
    (Named)                                     \
    (Native)                                    \
    (NearestSystemID)                           \
    (Neutron)                                   \
    (NextBetterPlanetType)                      \
    (NextCloserToOriginalPlanetType)            \
    (NextLargerPlanetSize)                      \
    (NextSmallerPlanetSize)                     \
    (NextOlderStarType)                         \
    (NextSystemID)                              \
    (NextTurnPopGrowth)                         \
    (NextYoungerStarType)                       \
    (NoDefaultCapacityEffect)                   \
    (NoDefaultFuelEffect)                       \
    (NoDefaultSpeedEffect)                      \
    (NoDefaultStealthEffect)                    \
    (NoDefaultStructureEffect)                  \
    (None)                                      \
    (NoOp)                                      \
    (NoStar)                                    \
    (NoStringtableLookup)                       \
    (Not)                                       \
    (number)                                    \
    (Number)                                    \
    (NumberOf)                                  \
    (NumShips)                                  \
    (NumStarlanes)                              \

#define TOKEN_SEQ_8                             \
    (object)                                    \
    (Object)                                    \
    (ObjectType)                                \
    (Ocean)                                     \
    (Off)                                       \
    (On)                                        \
    (OneOf)                                     \
    (OnPlanet)                                  \
    (opinion)                                   \
    (Or)                                        \
    (Orange)                                    \
    (Orbit)                                     \
    (OrderedBombardedBy)                        \
    (OriginalType)                              \
    (OutpostsOwned)                             \
    (OwnedBy)                                   \
    (Owner)                                     \
    (OwnerHasShipPartAvailable)                 \
    (OwnerHasTech)                              \
    (parameters)                                \
    (part)                                      \
    (Part)                                      \
    (PartCapacity)                              \
    (PartClass)                                 \
    (PartDamage)                                \
    (Partial)                                   \
    (partname)                                  \
    (PartSecondaryStat)

#define TOKEN_SEQ_9                             \
    (parts)                                     \
    (PartOfClassInShipDesign)                   \
    (PartsInShipDesign)                         \
    (Passive)                                   \
    (PeaceWith)                                 \
    (Planet)                                    \
    (Planetbound)                               \
    (PlanetEnvironment)                         \
    (PlanetID)                                  \
    (planetsize)                                \
    (planettype)                                \
    (Playable)                                  \
    (PointDefense)                              \
    (Policy)                                    \
    (Poor)                                      \
    (Population)                                \
    (PopulationCenter)                          \
    (position)                                  \
    (prerequisites)                             \
    (PreviousSystemID)                          \
    (priority)                                  \
    (probability)                               \
    (ProducedByEmpire)                          \
    (ProducedByEmpireID)                        \
    (Producible)                                \
    (Product)                                   \
    (ProductionCenter)                          \
    (ProductionLocation)                        \
    (PropagatedSupplyRange)                     \
    (Property)                                  \
    (progress)

#define TOKEN_SEQ_10                            \
    (Radiated)                                  \
    (Radius)                                    \
    (Random)                                    \
    (RandomColonizableSpecies)                  \
    (RandomCompleteTech)                        \
    (RandomControlledSpecies)                   \
    (RandomEnqueuedTech)                        \
    (RandomResearchableTech)                    \
    (RandomTransferrableTech)                   \
    (RandomNumber)                              \
    (Range)                                     \
    (Real)                                      \
    (reason)                                    \
    (RebelTroops)                               \
    (Red)                                       \
    (Refinement)                                \
    (RemoveSpecial)                             \
    (RemoveStarlanes)                           \
    (Research)                                  \
    (Researchable)                              \
    (researchcost)                              \
    (researchturns)                             \
    (ResourceSupplyConnected)                   \
    (ResupplyableBy)                            \
    (Retain)                                    \
    (RMS)                                       \
    (RootCandidate)                             \
    (round)                                     \
    (scope)                                     \
    (SecondaryStat)

#define TOKEN_SEQ_11                            \
    (SetAggressive)                             \
    (SetCapacity)                               \
    (SetConstruction)                           \
    (SetDamage)                                 \
    (SetDefense)                                \
    (SetDefensive)                              \
    (SetDestination)                            \
    (SetDetection)                              \
    (SetEmpireCapital)                          \
    (SetEmpireMeter)                            \
    (SetEmpireTechProgress)                     \
    (SetEmpireStockpile)                        \
    (SetFuel)                                   \
    (SetHappiness)                              \
    (SetIndustry)                               \
    (SetInfluence)                              \
    (SetMaxCapacity)                            \
    (SetMaxDamage)                              \
    (SetMaxDefense)                             \
    (SetMaxFuel)                                \
    (SetMaxSecondaryStat)                       \
    (SetMaxShield)                              \
    (SetMaxStockpile)                           \
    (SetMaxStructure)                           \
    (SetMaxSupply)                              \
    (SetMaxTroops)                              \
    (SetObstructive)                            \
    (SetOverlayTexture)                         \
    (SetOwner)                                  \
    (SetPassive)                                \
    (SetPlanetSize)                             \
    (SetPlanetType)                             \
    (SetPopulation)

#define TOKEN_SEQ_12                            \
    (SetRange)                                  \
    (SetRebelTroops)                            \
    (SetResearch)                               \
    (SetSecondaryStat)                          \
    (SetShield)                                 \
    (SetSize)                                   \
    (SetSpecialCapacity)                        \
    (SetSpecies)                                \
    (SetSpeciesOpinion)                         \
    (SetSpeed)                                  \
    (SetStarType)                               \
    (SetStealth)                                \
    (SetStockpile)                              \
    (SetStructure)                              \
    (SetSupply)                                 \
    (SetTargetConstruction)                     \
    (SetTargetHappiness)                        \
    (SetTargetIndustry)                         \
    (SetTargetInfluence)                        \
    (SetTargetPopulation)                       \
    (SetTargetResearch)                         \
    (SetTexture)                                \
    (SetTroops)                                 \
    (SetVisibility)

#define TOKEN_SEQ_13                            \
    (Shield)                                    \
    (ShipDesign)                                \
    (ShipDesignCost)                            \
    (ShipDesignOrdering)                        \
    (ShipDesignsDestroyed)                      \
    (ShipDesignsInProduction)                   \
    (ShipDesignsLost)                           \
    (ShipDesignsOwned)                          \
    (ShipDesignsProduced)                       \
    (ShipDesignsScrapped)                       \
    (Ship)                                      \
    (ShipHull)                                  \
    (ShipPart)                                  \
    (ShipPartMeter)                             \
    (ShipPartsOwned)                            \
    (ships)                                     \
    (short_description)                         \
    (ShortestPath)                              \
    (ShortRange)                                \
    (shots)                                     \
    (sign)                                      \
    (sin)                                       \
    (size)                                      \
    (Size)                                      \
    (SizeAsDouble)

#define TOKEN_SEQ_14                            \
    (Slot)                                      \
    (slots)                                     \
    (SlotsInHull)                               \
    (SlotsInShipDesign)                         \
    (SlotType)                                  \
    (Small)                                     \
    (sortkey)                                   \
    (Source)                                    \
    (Spacebound)                                \
    (spawnlimit)                                \
    (spawnrate)                                 \
    (Special)                                   \
    (SpecialAddedOnTurn)                        \
    (SpecialCapacity)                           \
    (species)                                   \
    (Species)                                   \
    (SpeciesCensusOrdering)                     \
    (SpeciesColoniesOwned)                      \
    (SpeciesContentOpinion)                     \
    (SpeciesEmpireOpinion)                      \
    (SpeciesSpeciesOpinion)                     \
    (SpeciesPlanetsBombed)

#define TOKEN_SEQ_15                            \
    (SpeciesPlanetsDepoped)                     \
    (SpeciesPlanetsInvaded)                     \
    (SpeciesShipsDestroyed)                     \
    (SpeciesShipsLost)                          \
    (SpeciesShipsOwned)                         \
    (SpeciesShipsProduced)                      \
    (SpeciesShipsScrapped)                      \
    (speed)                                     \
    (Speed)                                 \
    (Spread)                                    \
    (stackinggroup)                             \
    (Star)                                      \
    (StarType)                                  \
    (Stationary)                                \
    (Statistic)                                 \
    (StDev)                                     \
    (stealth)                                   \
    (Stealth)                                   \
    (Stockpile)                                 \
    (String)                                    \
    (StringList)                                \
    (structure)                                 \
    (Structure)                                 \
    (Sum)                                       \
    (Supply)                                    \
    (SupplyingEmpire)                           \
    (Swamp)                                     \
    (System)                                    \
    (SystemID)

#define TOKEN_SEQ_16                            \
    (tag)                                       \
    (tags)                                      \
    (target)                                    \
    (Target)                                    \
    (TargetConstruction)                        \
    (TargetHappiness)                           \
    (TargetIndustry)                            \
    (TargetInfluence)                           \
    (TargetPopulation)                          \
    (TargetResearch)                            \
    (Tech)                                      \
    (Terran)                                    \
    (TestValue)                                 \
    (TheEmpire)                                 \
    (Theory)                                    \
    (ThisBuilding)                              \
    (ThisField)                                 \
    (ThisHull)                                  \
    (ThisPart)                                  \
    (ThisPolicy)                                \
    (ThisTech)                                  \
    (ThisSpecies)                               \
    (ThisSpecial)                               \
    (Tiny)                                      \
    (Toggle)                                    \
    (TopPriorityEnqueuedTech)                   \
    (TopPriorityResearchableTech)               \
    (TopPriorityTransferrableTech)              \
    (OrderedAlternativesOf)                     \
    (Toxic)                                     \
    (Trade)

#define TOKEN_SEQ_17                            \
    (Troops)                                    \
    (Tundra)                                    \
    (Turn)                                      \
    (TurnPolicyAdopted)                         \
    (TurnsSinceFocusChange)                     \
    (TurnTechResearched)                        \
    (type)                                      \
    (Uninhabitable)                             \
    (UniverseCentreX)                           \
    (UniverseCentreY)                           \
    (UniverseWidth)                             \
    (unlock)                                    \
    (Unowned)                                   \
    (Unproducible)                              \
    (Unresearchable)                            \
    (UpgradeVisibility)                         \
    (UsedInDesignID)                            \
    (UserString)                                \
    (uuid)                                      \
    (value)                                     \
    (Value)                                     \
    (Victory)                                   \
    (VisibleToEmpire)                           \
    (visibility)                                \
    (White)                                     \
    (WithinDistance)                            \
    (WithinStarlaneJumps)                       \
    (x)                                         \
    (X)                                         \
    (y)                                         \
    (Y)                                         \
    (Yellow)

#endif
