find_program(GODOT_EXECUTABLE NAMES godot3-server godot3-headless godot-headless godot3 godot godot3-runner REQUIRED)
execute_process(COMMAND ${GODOT_EXECUTABLE} --version OUTPUT_VARIABLE GODOT_VERSION)
string(STRIP "${GODOT_VERSION}" GODOT_VERSION)
message("Found godot at ${GODOT_EXECUTABLE} version ${GODOT_VERSION}")
file(APPEND "$ENV{GITHUB_OUTPUT}" "godot=${GODOT_EXECUTABLE}\n")
file(APPEND "$ENV{GITHUB_OUTPUT}" "version=${GODOT_VERSION}\n")
