#!/usr/bin/perl -w
$DEBUG = 0;

@DIRLIST = ("Empire","util","universe","UI","network");

undef %SPECIAL; # List of files that compile differently for SERVER and CLIENT
undef %COMMON;  # List of files that are identical for SERVER and CLIENT

foreach $DIRNAME (@DIRLIST) {

    chdir $DIRNAME;



# Search for occurence of #ifdef FREEORION_BUILD
# Since some headers may contain inline-template definitions 
# that can be conditional compiled in, we need to check all FO-Sourcefiles
# a specific file depends on (#include's). If one files
# is or depends on such a conditionally compiled file, we must also move 
# the "#includer" to SPECIAL

    while ($file = glob "*.cpp *.h *.c") {
	open FILE, $file;
	while (<FILE>) {
	    if (m/\s*#\s*if(?:n?def)? \s*FREEORION_BUILD_([^\s]+)/) {
		$SPECIAL{"$DIRNAME/$file"} = 1;
		goto done;
	    }
	}
	$COMMON{"$DIRNAME/$file"} = 1;
      done:
	close FILE;
    }
    chdir "..";
}

# find and store dependencies
foreach $filename (keys %COMMON) {
    open FILE, $filename;
    my @DepThisFile;
    while (<FILE>) {
	if (m/\s*#\w*include\s*(<|")([^>"]+)\1\s*$/) {
	    ($inc = $2) =~ s|^.*/([^/]+)$|$1|;
	    push @DepThisFile, $inc;
	}
    }
    $Depends{$filename} = "@DepThisFile";
    close FILE;
}
	

# now move all files to %SPECIAL that depend on a file already in %SPECIAL
### PATHNAMES ARE IGNORED HERE! IT IS ASSUMED THAT FILENAMES ARE UNIQUE
### BETWEEN DIRECTORIES!

recheck_deps:
$changed = 0;
FILECHECK: while ( ($filename,$deplist) = each(%Depends) ) {
    foreach $fn (split (/ /,$deplist)) {
	if (grep {/$fn/} (keys %SPECIAL)) {
	    # Move filename from COMMON to SPECIAL
	    $SPECIAL{$filename} = 1;
	    delete $COMMON{$filename};

	    # We do not need to check this file anymore
	    delete $Depends{$filename};
	    print "Added $filename, it depends on $fn\n" if $DEBUG;
	    $changed = 1;
	    next FILECHECK;
	}
    }
}

goto recheck_deps if $changed;

# Now create the Makefile.am's

foreach $DIRNAME (@DIRLIST) {
    $d = lc $DIRNAME;
    
    open AMFILE,">$DIRNAME/Makefile.am";
    
    print AMFILE "# This Makefile.am was generated by $0\n# at ". gmtime() ."\n# **ALL CHANGES WILL BE OVERWRITTEN**\n";
    print AMFILE"AM_CPPFLAGS = \@GIGI_CFLAGS\@ \@GIGISDL_CFLAGS\@ \@GIGINET_CFLAGS\@ \@SDL_CFLAGS\@ \@FT2_CFLAGS\@\n";
    print AMFILE "AM_CXXFLAGS = -g3 -Wall\n\n";

    printf AMFILE ("%-70s", "libFO${d}_common_a_SOURCES = ");
    foreach (grep {m|$DIRNAME/|} (sort keys %COMMON)) {
	printf AMFILE (" \\\n%-70s", "\@top_srcdir\@/$_");
    }
    print AMFILE "\n\n";
    
    print AMFILE "noinst_LIBRARIES = libFO${d}-common.a";

    if ( (grep {m|$DIRNAME/|} (keys %SPECIAL)) == 0) {
	print AMFILE"\n";
	goto fini;
    }

    foreach $type (("server","human","ai")) {
	print AMFILE " libFO${d}-${type}.a";
    }
    print AMFILE "\n\n";
    foreach $type (("server","human","ai")) {
	print AMFILE "libFO${d}_${type}_a_CPPFLAGS = -DFREEORION_BUILD_".(uc $type)." \$(AM_CPPFLAGS)\n\n";
	printf AMFILE ("%-70s", "libFO${d}_${type}_a_SOURCES = ");
	foreach (grep {m|$DIRNAME/|} (sort keys %SPECIAL)) {
	    printf AMFILE (" \\\n%-70s", "\@top_srcdir\@/$_");
	}
	print AMFILE "\n\n";
    }
  fini:
    print "$DIRNAME/Makefile.am created\n" if $DEBUG;
    close AMFILE;
}
