#!/bin/bash

for FILE in `find . -name Makefile`; 
do
    mv $FILE ${FILE}.autoconfed
done
for FILE in `find . -name Makefile.CVS`; do
    mv $FILE ${FILE/.CVS/}
done

cvs $@

for FILE in `find . -name Makefile`; do
    mv $FILE ${FILE}.CVS
done
for FILE in `find . -name Makefile.autoconfed`; do
    mv $FILE ${FILE/.autoconfed/}
done

