name: 'cmake-build'
description: 'Build FreeOrion with cmake'
inputs:
  mvc:
    description: 'Flag to handle cases'
    required: true
  generator-name:
    description: 'generator-name'
    required: true
  toolset-spec:
    description: 'toolset-spec'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download SDK
      id: download-sdk
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: https://github.com/freeorion/freeorion-sdk/releases/download/v14/FreeOrionSDK_14_MSVC-v143-Win32.zip
        target: ../
    - name: Add msbuild to PATH
      if:   inputs.mvc == '2019'
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[16.0,16.30)'
    - name: Add msbuild to PATH
      if: inputs.mvc == '2022'
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true
    - name: Configure
      shell: pwsh
      run: |
        Remove-Item -LiteralPath "C:/hostedtoolcache/windows/Python/" -Force -Recurse # Ensure that system Python is not used
        unzip -q ../${{ steps.download-sdk.outputs.filename }} -d ..
        mkdir build
        pushd build
        cmake -G "${{ inputs.generator-name }}" -T ${{inputs.toolset-spec }} -A Win32 -DBUILD_TESTING=On -DBUILD_CLIENT_GODOT=On -DCMAKE_C_FLAGS=/MP -DCMAKE_CXX_FLAGS=/MP ..
    - name: Build
      shell: pwsh
      run: |
        pushd build
        cmake --build . --config "Release" -- /maxcpucount /property:BuildInParallel=true /property:CL_MPCount=2 /verbosity:minimal
    - name: Test
      shell: pwsh
      run: |
        pushd build
        $env:Path += ";$($pwd.Path)\\Release"
        cmake --build . --config "Release" --target unittest
    - name: Download Godot
      id: download-godot
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_win32.exe.zip
        target: ../
    - name: Download Mesa
      id: download-mesa
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: https://downloads.fdossena.com/geth.php?r=mesa-latest
        target: ../
    - name: Install Godot and dependencies
      shell: pwsh
      run: |
        unzip -q ../${{ steps.download-godot.outputs.filename }} -d build/Release
        mkdir build/Release/Godot_v3.2.3-stable_win32.exe.local
        pushd build/Release/Godot_v3.2.3-stable_win32.exe.local
        7z e ../../../../${{ steps.download-mesa.outputs.filename }}
    - name: Test Godot
      shell: pwsh
      run: |
        $env:Path += ";$($pwd.Path)\\build\\Release"
        .\build\Release\Godot_v3.2.3-stable_win32.exe --no-window --disable-render-loop --video-driver GLES2 --verbose -s --path godot addons/gut/gut_cmdln.gd -gdir=res://test/ -ginclude_subdirs -gexit
