name: 'cmake-build'
description: 'Build FreeOrion with cmake'
# inputs:
#  directory:
#    description: 'Directory to check'
#    required: true
#  config-file:
#    description: 'Flake8 config'
#    required: true
runs:
  using: "composite"
  steps:
    - name: Download SDK
      id: download-sdk
      uses: suisei-cn/actions-download-file@v1
      with:
        url: https://github.com/freeorion/freeorion-sdk/releases/download/v13/FreeOrionSDK_13_MSVC-v141-Win32.zip
        target: ../
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[16.0,16.30)'
    - name: Configure
      shell: pwsh
      run: |
        unzip -q ../${{ steps.download-sdk.outputs.filename }} -d ..
        mkdir build
        pushd build
        cmake -G "Visual Studio 16 2019" -T v142 -A Win32 -DBUILD_TESTING=On -DBUILD_CLIENT_GODOT=On -DCMAKE_C_FLAGS=/MP -DCMAKE_CXX_FLAGS=/MP ..
    - name: Build
      shell: pwsh
      run: |
        pushd build
        cmake --build . --config "Release" -- /maxcpucount /property:BuildInParallel=true /property:CL_MPCount=2 /verbosity:minimal
    - name: Test
      shell: pwsh
      run: |
        pushd build
        $env:Path += ";$($pwd.Path)\\Release"
        cmake --build . --config "Release" --target unittest
    - name: Download Godot
      id: download-godot
      uses: suisei-cn/actions-download-file@v1
      with:
        url: https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_win32.exe.zip
        target: ../
    - name: Download Mesa
      id: download-mesa
      uses: suisei-cn/actions-download-file@v1
      with:
        url: https://downloads.fdossena.com/geth.php?r=mesa-latest
        target: ../
    - name: Install Godot and dependencies
      shell: pwsh
      run: |
        unzip -q ../${{ steps.download-godot.outputs.filename }} -d build/Release
        mkdir build/Release/Godot_v3.2.3-stable_win32.exe.local
        pushd build/Release/Godot_v3.2.3-stable_win32.exe.local
        7z e ../../../../${{ steps.download-mesa.outputs.filename }}
    - name: Test Godot
      shell: pwsh
      run: |
        $env:Path += ";$($pwd.Path)\\build\\Release"
        .\build\Release\Godot_v3.2.3-stable_win32.exe --no-window --disable-render-loop --video-driver GLES2 --verbose -s --path godot addons/gut/gut_cmdln.gd -gdir=res://test/ -ginclude_subdirs -gexit
    - name: Generate binaries only
      shell: pwsh
      run: |
        pushd build
        cpack -V -C Release -G ZIP -D CPACK_ARCHIVE_COMPONENT_INSTALL=ON -D CPACK_MONOLITHIC_INSTALL=OFF -D CPACK_COMPONENTS_ALL=binaries
