
#ifndef _FREEORION_CLIENTEMPIRE_H_
#define _FREEORION_CLIENTEMPIRE_H_

#ifndef _FREEORION_EMPIREMANAGER_H_
#include "EmpireManager.h"
#endif

/**
* ClientEmpire is the client version of the EmpireManager
*
*/
class ClientEmpire : public EmpireManager
{
public:
    ClientEmpire();
   
    /**
    *  Handles an update for this client.  
    *  The XMLElement should be an XMLDiff for the empires in this client
    *  manager (that is, produced by ServerEmpire::CreateClientEmpireUpdate()
    *
    */
    bool HandleEmpireElementUpdate( GG::XMLElement empireElement);

    /**
    *  Takes an XMLElement representing a list of sitrep events
    *  The list will be decoded, one entry at a time, and the entries
    *  will be added to the sitrep of the empire to whom they belong.
    * 
    *  The XMLElement passed into this method should be identical to
    *  that generated by ServerEmpire::CreateClientSitrepUpdate()
    *
    */
    bool HandleSitRepElementUpdate( GG::XMLElement sitRepElement);


protected:
    
    
};


#endif

