
#include "ClientEmpire.h"


ClientEmpire::ClientEmpire()
{
    // no worries yet
}
   
/**
*  Handles an update for this client.  
*  The XMLElement should be an XMLDiff for the empires in this client
*  manager (that is, produced by ServerEmpire::CreateClientEmpireUpdate()
*
*/
bool ClientEmpire::HandleEmpireElementUpdate( GG::XMLElement empireElement)
{
    // FINISH ME!
    return true;
}

/**
*  Takes an XMLElement representing a list of sitrep events
*  The list will be decoded, one entry at a time, and the entries
*  will be added to the sitrep of the empire to whom they belong.
* 
*  The XMLElement passed into this method should be identical to
*  that generated by ServerEmpire::CreateClientSitrepUpdate()
*
*/
bool ClientEmpire::HandleSitRepElementUpdate( GG::XMLElement sitRepElement)
{
    // FINISH ME!!
    return true;
}
