from focs._types import (
    _ID,
    _BuildingType,
    _Condition,
    _Empire,
    _EmpireId,
    _EnqueuedObjectType,
    _FloatParam,
    _Focus,
    _IntParam,
    _PlanetEnvironment,
    _PlanetSize,
    _PlanetType,
    _Resource,
    _ShipPartClass,
    _SpeciesValue,
    _StarType,
    _StringParam,
    _SystemID,
)

System = _Condition()
Ship = _Condition()
Monster = _Condition()
Armed = _Condition()
Unowned = _Condition()
Capital = _Condition()
IsHuman = _Condition()
Fleet = _Condition()
Stationary = _Condition()
NoOpCondition = _Condition()
IsSource = _Condition()
IsRootCandidate = _Condition()
IsTarget = _Condition()
CanColonize = _Condition()
IsAnyObject = _Condition()
CanProduceShips = _Condition()
NoObject = _Condition()

ContentFocus = _Focus()

def Object(id) -> _Condition: ...
def DesignHasPartClass(name: _ShipPartClass, low: _IntParam = ..., high: _IntParam = ...) -> _Condition: ...
def Enqueued(
    *,
    type: _EnqueuedObjectType | None = None,
    subtype: str | None = None,
    name: str = "",
    low: _IntParam = ...,
    high: _IntParam = ...,
    empire: _EmpireId = ...,
) -> _Condition: ...
def TurnTechResearched(*, empire: _EmpireId, name: str) -> _Condition: ...
def IsBuilding(
    *,
    name: str | _BuildingType | list[str | _BuildingType] | None = None,
    subtype: str | None = None,
) -> _Condition: ...
def Number(*, low: _IntParam = ..., high: _IntParam = ..., condition: _Condition = ...) -> _Condition: ...
def Planet(
    *,
    type: list[_PlanetType] = ...,
    environment: list[_PlanetEnvironment] = ...,
    size: list[_PlanetSize] = ...,
    species: _SpeciesValue = ...,
) -> _Condition: ...
def Star(*, type: list[_StarType]) -> _Condition: ...
def Location(*, type: _Focus, name: _SpeciesValue, name2: _Focus | str) -> _Condition: ...
def HasSpecies(*, name: list[_StringParam] | _StringParam | None = None) -> _Condition: ...
def IsField(*, name: list[_StringParam] | None = None) -> _Condition: ...
def Population(*, low: _FloatParam = ..., high: _FloatParam = ...) -> _Condition: ...
def Industry(*, low: _FloatParam = ..., high: _FloatParam = ...) -> _Condition: ...
def Size(*, low: _FloatParam = ..., high: _FloatParam = ...) -> _Condition: ...
def TargetPopulation(*, low: _FloatParam = ..., high: _FloatParam = ...) -> _Condition: ...
def SpeciesLikes(*, name: _Focus | _BuildingType | _SpeciesValue) -> _Condition: ...
def SpeciesDislikes(*, name: _Focus | _BuildingType | _SpeciesValue) -> _Condition: ...
def Homeworld(*, name: list[_SpeciesValue] = ...) -> _Condition: ...
def HasTag(*, name: str) -> _Condition: ...
def VisibleToEmpire(*, empire: _EmpireId) -> _Condition: ...
def ContainedBy(condition: _Condition, /) -> _Condition: ...
def HasSpecial(*, name: str) -> _Condition: ...
def OwnerHasTech(*, name: str) -> _Condition: ...
def InGame() -> _Condition: ...
def InSystem(*, id: _SystemID = _SystemID()) -> _Condition: ...
def Described(*, description: str, condition: _Condition) -> _Condition: ...
def MinimumNumberOf(number: _IntParam, sortkey: _FloatParam, condition: _Condition) -> _Condition: ...
def MaximumNumberOf(number: _IntParam, sortkey: _FloatParam, condition: _Condition) -> _Condition: ...
def NumberOf(number: _IntParam, condition: _Condition) -> _Condition: ...
def UniqueNumberOf(*, number: _IntParam, condition: _Condition, sortkey) -> _Condition: ...
def TargetIndustry(*, low: _FloatParam) -> _Condition: ...
def Stealth(*, high: _FloatParam) -> _Condition: ...
def Speed(*, low: _FloatParam) -> _Condition: ...
def Happiness(*, low: _FloatParam) -> _Condition: ...
def Focus(*, type: list[str]) -> _Condition: ...
def Random(*, probability: _FloatParam) -> _Condition: ...
def OwnedBy(*, affiliation: _EmpireId = _Empire(), empire: _EmpireId = _Empire()) -> _Condition: ...
def WithinStarlaneJumps(*, jumps: _IntParam, condition: _Condition) -> _Condition: ...
def WithinDistance(*, distance: _FloatParam, condition: _Condition) -> _Condition: ...
def ResourceSupplyConnected(*, empire: _EmpireId, condition: _Condition) -> _Condition: ...
def Contains(scope: _Condition, /) -> _Condition: ...
def Turn(*, high: _FloatParam = ..., low: _FloatParam = ...) -> _Condition: ...
def Structure(*, low: _FloatParam = ..., high: _FloatParam = ...) -> _Condition: ...
def ResupplyableBy(*, empire: _EmpireId) -> _Condition: ...
def DesignHasPart(*, name: str, low: _IntParam = ..., high: _IntParam = ...) -> _Condition: ...
def EmpireHasAdoptedPolicy(*, name: str, empire: _EmpireId = _Empire()) -> _Condition: ...
def ProducedByEmpire(*, empire: _Empire) -> _Condition: ...
def HasStarlane(from_: _Condition) -> _Condition: ...
def HasDesign(name: _StringParam) -> _Condition: ...
def StarlaneToWouldCrossExistingStarlane(from_: _Condition) -> _Condition: ...
def StarlaneToWouldBeAngularlyCloseToExistingStarlane(from_: _Condition, maxdotprod: _FloatParam) -> _Condition: ...
def StarlaneToWouldBeCloseToObject(*, distance: _FloatParam, from_: _Condition, closeto: _Condition) -> _Condition: ...
def HasEmpireStockpile(
    *, empire: _EmpireId, resource: _Resource, low: _IntParam = ..., high: _IntParam = ...
) -> _Condition: ...
def OnPlanet(*, id: _ID) -> _Condition: ...
