from typing import Any, overload

from focs._types import (
    _Affilation,
    _Condition,
    _Effect,
    _EffectGroup,
    _Empire,
    _EmpireId,
    _FloatParam,
    _IntParam,
    _ItemType,
    _PlanetSize,
    _PlanetType,
    _Resource,
    _SpeciesValue,
    _StarType,
    _StringParam,
    _ValueParam,
)

class _Item: ...

def Item(type: _ItemType, name: str) -> _Item: ...
def MoveInOrbit(
    speed: _FloatParam,
    focus: _Condition = ...,
    x: _FloatParam = ...,
    y: _FloatParam = ...,
) -> _Effect: ...
def CreatePlanet(
    type: _PlanetType,
    planetsize: _PlanetSize,
    name: _StringParam = ...,
    initial_effects: list[_Effect] = ...,
) -> _Effect: ...

Destroy = _Effect()

NoOpEffect = _Effect()

def Conditional(
    *,
    condition: _Condition | bool,
    effects: list[_Effect],
    else_: list[_Effect] = ...,
) -> _Effect: ...
def AddSpecial(*, name: str, capacity: _FloatParam = ...) -> _Effect: ...
def RemoveSpecial(*, name: str) -> _Effect: ...
def SetMaxShield(*, value: _FloatParam, accountinglabel: str = "") -> _Effect: ...
def SetMaxStructure(*, value: _FloatParam, accountinglabel: str = "") -> _Effect: ...
def SetEmpireStockpile(*, resource: _Resource, value: _FloatParam) -> _Effect: ...
def SetShield(*, value: _FloatParam) -> _Effect: ...
def SetTargetIndustry(*, value: _FloatParam) -> _Effect: ...
def SetDetection(*, value: _FloatParam) -> _Effect: ...
def SetStructure(*, value: _FloatParam) -> _Effect: ...
def SetFuel(*, value: _FloatParam) -> _Effect: ...
def SetSize(*, value: _FloatParam) -> _Effect: ...
def SetDefense(*, value: _FloatParam) -> _Effect: ...
def SetMaxTroops(*, value: _FloatParam) -> _Effect: ...
def SetStockpile(*, value: _FloatParam) -> _Effect: ...
def SetMaxStockpile(*, value: _FloatParam, accountinglabel: str = "") -> _Effect: ...
def SetTargetHappiness(*, value: _FloatParam) -> _Effect: ...
def GiveEmpirePolicy(*, name: str, empire: _EmpireId = _Empire()) -> _Effect: ...
def SetVisibility(empire: _EmpireId, visibility: Any, affiliation=_Affilation()) -> _Effect: ...
def SetPopulation(*, value: _FloatParam) -> _Effect: ...
def SetPlanetType(*, type: _PlanetType) -> _Effect: ...
def SetSpeed(*, value: _FloatParam) -> _Effect: ...
def SetSpecies(*, name: _StringParam) -> _Effect: ...
def SetTroops(*, value: _FloatParam) -> _Effect: ...
def SetMaxDefense(*, value: _FloatParam) -> _Effect: ...
def SetSupply(*, value: _FloatParam) -> _Effect: ...
def SetTargetResearch(*, value: _FloatParam) -> _Effect: ...
def SetHappiness(*, value: _FloatParam) -> _Effect: ...
def SetPlanetSize(*, planetsize: _PlanetSize) -> _Effect: ...
def SetMaxSupply(*, value: _FloatParam) -> _Effect: ...
def SetMaxFuel(*, value: _FloatParam) -> _Effect: ...
def SetResearch(*, value: _FloatParam) -> _Effect: ...
def SetIndustry(*, value: _FloatParam) -> _Effect: ...
def SetInfluence(*, value: _FloatParam) -> _Effect: ...
def SetSpeciesTargetOpinion(*, species: _SpeciesValue, empire: _EmpireId, opinion: _FloatParam) -> _Effect: ...
def SetSpeciesOpinion(*, species: _SpeciesValue, empire: _EmpireId, opinion: _FloatParam) -> _Effect: ...
def SetTargetPopulation(*, value: _FloatParam, accountinglabel: str = "") -> _Effect: ...
def SetTargetInfluence(*, value: _FloatParam) -> _Effect: ...
def SetTargetConstruction(*, value: _FloatParam) -> _Effect: ...
def SetConstruction(*, value: _FloatParam) -> _Effect: ...
def SetRebelTroops(*, value: _FloatParam) -> _Effect: ...
def SetStealth(*, value: _FloatParam) -> _Effect: ...
def CreateBuilding(*, type: str) -> _Effect: ...
def CreateShip(*, designname: str, empire=_Empire(), species: str | _SpeciesValue = "") -> _Effect: ...
def SetCapacity(*, partname: str, value: _FloatParam) -> _Effect: ...
def SetSecondaryStat(*, partname: str, value: _FloatParam) -> _Effect: ...
def SetMaxDamage(*, partname: str, value: _FloatParam) -> _Effect: ...
def SetMaxCapacity(*, partname: str, value: _FloatParam) -> _Effect: ...
def SetMaxSecondaryStat(*, partname: str, value: _FloatParam) -> _Effect: ...
def MoveTo(*, destination: _Condition) -> _Effect: ...
def MoveTowards(*, speed: _FloatParam, target=_Condition(), x: _FloatParam = ..., y: _FloatParam = ...) -> _Effect: ...
def SetStarType(*, type: _StarType) -> _Effect: ...
def SetEmpireMeter(*, empire: _EmpireId, meter: str, value: _FloatParam) -> _Effect: ...
def SetOwner(*, empire: _EmpireId) -> _Effect: ...
def SetSpecialCapacity(name: str | _SpeciesValue, capacity: _ValueParam) -> _Effect: ...
@overload
def GenerateSitRepMessage(
    *,
    NoStringtableLookup: bool = True,
    message: str,
    label: str,
    empire: _EmpireId = ...,
    parameters: dict[str, Any] = ...,
    icon: str = "",
) -> _Effect: ...
@overload
def GenerateSitRepMessage(
    *,
    NoStringtableLookup: bool = True,
    message: str,
    label: str,
    parameters: dict[str, Any] = ...,
    affiliation: _Affilation = ...,
    condition: _Condition = ...,
    icon: str = "",
) -> _Effect: ...
def GiveEmpireTech(*, name: str, empire: _EmpireId = _Empire()) -> _Effect: ...
def Victory(*, reason: str) -> _Effect: ...
def CreateField(*, type: _StringParam, size: _IntParam) -> _Effect: ...
def AddStarlanes(endpoint: _Condition) -> _Effect: ...
def RemoveStarlanes(endpoint: _Condition) -> _Effect: ...
def SetEmpireCapital() -> _Effect: ...
def EffectsGroup(
    *,
    scope: _Condition,
    effects: list[_Effect] | _Effect,
    activation: bool | _Condition | None = None,
    description: str = "",
    priority=None,
    accountinglabel: str = "",
    stackinggroup: str = "",
) -> _EffectGroup: ...
