from __future__ import annotations

from typing import Any, TypeVar, overload

# Default value for int keyword arguments, use it when default value is not clear
from focs._types import (
    _ID,
    _T,
    _T_IN,
    _T_OUT,
    _Aggregator,
    _BuildingType,
    _Condition,
    _ConditionalComposition,
    _DesignID,
    _Effect,
    _EffectGroup,
    _Empire,
    _EmpireId,
    _FleetID,
    _FloatParam,
    _Focus,
    _IntParam,
    _MeterType,
    _PlanetEnvironment,
    _PlanetId,
    _PlanetSize,
    _PlanetType,
    _Resource,
    _SpeciesValue,
    _StarType,
    _StringParam,
    _SystemID,
    _ValueParam,
    _Visibility,
)

Capacity = _MeterType()
MaxCapacity = _MeterType()
SecondaryStat = _MeterType()
MaxSecondaryStat = _MeterType()

Blue = _StarType()
White = _StarType()
Orange = _StarType()
Yellow = _StarType()
Red = _StarType()
Neutron = _StarType()
NoStar = _StarType()
BlackHole = _StarType()

def Object(id) -> _Condition: ...

Invisible = _Visibility()
Basic = _Visibility()
Partial = _Visibility()
Full = _Visibility()

Tiny = _PlanetSize()
Small = _PlanetSize()
Medium = _PlanetSize()
Large = _PlanetSize()
Huge = _PlanetSize()

Swamp = _PlanetType()
Toxic = _PlanetType()
Inferno = _PlanetType()
Radiated = _PlanetType()
Barren = _PlanetType()
Tundra = _PlanetType()
Desert = _PlanetType()
Terran = _PlanetType()
Ocean = _PlanetType()
AsteroidsType = _PlanetType()
GasGiantType = _PlanetType()

Good = _PlanetEnvironment()
Adequate = _PlanetEnvironment()
Poor = _PlanetEnvironment()
Hostile = _PlanetEnvironment()
Uninhabitable = _PlanetEnvironment()

ThisSpecies = _SpeciesValue()
ThisBuilding = _BuildingType()

class _EnqueuedObjectType: ...

BuildBuilding = _EnqueuedObjectType()

AnyEmpire = _Empire()

class _Affilation(_Empire): ...

EnemyOf = _Affilation()
AllyOf = _Affilation()
CurrentTurn = 0

ContentFocus = _Focus()

class _SystemInfo:
    LastTurnBattleHere: int
    ID: _ID
    NumStarlanes: int

class _Object:
    ID: _ID
    System: _SystemInfo
    SystemID: _SystemID
    X: int
    Y: int
    Owner: _Empire
    Age: int
    CreationTurn: int
    # Unowned
    # OwnedBy
    # Specials??
    # HasSpecial
    # SpecialAddedOnTurn
    # SpecialCapacity

class _Planet(_Object):
    Species: _SpeciesValue
    PlanetID: _PlanetId
    Focus: _Focus
    TurnsSinceFocusChange: int
    HabitableSize: float
    PlanetType: _PlanetType
    OriginalType: _PlanetType
    NextBestPlanetType: _PlanetType
    LastTurnAnnexed: int
    LastTurnConquered: int
    LastInvadedByEmpire: _Empire
    LastTurnColonized: int
    LastColonizedByEmpire: _Empire
    TurnsSinceColonization: int
    Construction: Any
    TargetConstruction: float
    Happiness: float
    TargetHappiness: float
    Industry: float
    TargetIndustry: float
    Influence: float
    TargetInfluence: float
    Population: float
    TargetPopulation: float
    Research: float
    TargetResearch: float
    Stealth: float
    Stockpile: float
    MaxStockpile: float
    MaxSupply: float
    MaxDefense: float
    MaxShield: float
    MaxTroops: float

class _Ship(_Object):
    Species: _SpeciesValue
    DesignID: _DesignID
    Fleet: _Fleet
    FleetID: _FleetID
    LastTurnResupplied: int
    OrderedColonizePlanetID: _PlanetId
    Speed: int
    Research: float
    Industry: float
    MaxFuel: float
    Stealth: float
    MaxStructure: float
    MaxShield: float
    MaxTroops: float
    Structure: float
    DestroyFightersPerBattleMax: float
    DamageStructurePerBattleMax: float

class _Fleet(_Object):
    PreviousSystemID: _SystemID
    NextSystemID: _SystemID
    FleetID: _FleetID
    ProducedByEmpireID: _EmpireId

class _Building(_Object):
    ProducedByEmpireID: _EmpireId

class Source(_Planet, _Ship, _Fleet):
    """
    FOCS Source condition is IsSource, this class is for value ref Source.<something>
    """

    System: _SystemInfo
    CreationTurn: int
    Planet: _Planet

class LocalCandidate(_Planet, _Ship, _Fleet):
    LastTurnActiveInBattle: int
    LastTurnAttackedByShip: int
    ETA: int
    ArrivedOnTurn: int

class RootCandidate(_Planet, _Ship, _Fleet):
    ID: _ID
    Owner: _Empire
    PreviousSystemID: _SystemID
    SystemID: _SystemID
    Species: _SpeciesValue
    PlanetID: _PlanetId

class Target(_Planet, _Ship, _Fleet):
    PlanetID: _PlanetId

_O = TypeVar("_O", str, int, float)

class _ValuePlaceholder(_ConditionalComposition):
    def __call__(self, arg: _T) -> _T: ...
    def __add__(self, other: _T) -> _T: ...
    def __radd__(self, other: _T) -> _T: ...
    def __sub__(self, other: _T) -> _T: ...
    def __rsub__(self, other: _T) -> _T: ...
    def __mul__(self, other: _T) -> _T: ...
    def __rmul__(self, other: _T) -> _T: ...
    def __floordiv__(self, other: _T) -> _T: ...
    def __rfloordiv__(self, other: _T) -> _T: ...
    def __truediv__(self, other: _T) -> _T: ...
    def __rtruediv__(self, other: _T) -> _T: ...
    def __pow__(self, other: _T) -> _T: ...
    def __rpow__(self, other: _T) -> _T: ...

Value = _ValuePlaceholder()
ValueVisibility = _Visibility()

CountUnique = _Aggregator()
If = _Aggregator()
Count = _Aggregator()
HistogramMax = _Aggregator()
HistogramMin = _Aggregator()
HistogramSpread = _Aggregator()
Sum = _Aggregator()
Mean = _Aggregator()
RMS = _Aggregator()
Mode = _Aggregator()
Max = _Aggregator()
Min = _Aggregator()
Spread = _Aggregator()
StDev = _Aggregator()
Product = _Aggregator()

GalaxySize: _FloatParam = ...
GalaxyPlanetDensity: _FloatParam = ...

_args_type = int | float | str | _ValuePlaceholder

def NoOpValue(type_: type[_T], value: _args_type) -> _T: ...
def OneOf(type_: type[_T], *args: _args_type) -> _T: ...
def Abs(type_: type[_T], value: _args_type) -> _T: ...
def Floor(type_: type[_T], value: _FloatParam) -> _T: ...
@overload
def MinOf(type_: type[_T], *args: _args_type) -> _T: ...
@overload
def MinOf(type_: str, *args: _Visibility) -> int: ...
@overload
def MaxOf(type_: type[_T], *args: _args_type) -> _T: ...
@overload
def MaxOf(type_: str, *args: _Visibility) -> int: ...
def SpeciesColoniesOwned(*, empire: _Empire) -> int: ...
def DirectDistanceBetween(target: _ID, source: _ID, /) -> float: ...
def StatisticIf(type_: type[_T], *, condition: _Condition) -> _T: ...
def StatisticElse(type_: type[_T], *, condition: _Condition) -> _T: ...
def StatisticCount(type_: type[_T], *, condition: _Condition) -> _T: ...
@overload
def Statistic(type_: type[_T], aggregator: _Aggregator, /, value: _ValueParam, condition: _Condition) -> _T: ...
@overload
def Statistic(
    type_out: type[_T_OUT],
    type_of_value: type[_T_IN],
    aggregator: _Aggregator,
    /,
    value: _ValueParam | _SpeciesValue,
    condition: _Condition,
) -> _T_OUT: ...
def NamedReal(*, name: str, value: _FloatParam) -> float: ...
def NamedRealLookup(*, name: str) -> float: ...
def NamedIntegerLookup(*, name: str) -> int: ...
def JumpsBetween(source: _ID, target: _ID) -> int: ...
def SpecialCapacity(*, name: str, object: _ID) -> float: ...
def SpeciesShipsDestroyed(*, empire: _EmpireId, name: _SpeciesValue = ...) -> int: ...
def SpeciesShipsLost(*, empire: _EmpireId, name: _SpeciesValue) -> int: ...
def SpeciesEmpireTargetOpinion(*, species: _SpeciesValue, empire: _EmpireId) -> float: ...
def EmpireStockpile(*, empire: _EmpireId, resource: _Resource) -> float: ...
def PartCapacity(*, name: str) -> float: ...
def PartSecondaryStat(*, name: str) -> float: ...
def PartsInShipDesign(*, name: str, design: _DesignID) -> float: ...
def ShipPartMeter(*, part: str, meter: _MeterType, ship: _ID): ...
def UserString(name: str, /) -> str: ...
def EmpireMeterValue(*, empire: _EmpireId, meter: str) -> float: ...
def PlanetTypeDifference(*, from_: _PlanetType, to: _PlanetType) -> int: ...
def EffectsGroup(
    *,
    scope: _Condition,
    effects: list[_Effect] | _Effect,
    activation: bool | _Condition | None = None,
    description: str = "",
    priority=None,
    accountinglabel: str = "",
    stackinggroup: str = "",
) -> _EffectGroup: ...

# Conditions

CurrentContent = ""

def Enqueued(
    *, type: _EnqueuedObjectType, name: str = "", low: _IntParam = ..., high: _IntParam = ..., empire: _EmpireId = ...
) -> _Condition: ...
def TurnTechResearched(*, empire: _EmpireId, name: str) -> _Condition: ...
def IsBuilding(*, name: list[str | _BuildingType] = ...) -> _Condition: ...
def Number(*, low: int = ..., high: int = ..., condition: _Condition = ...) -> _Condition: ...
def Planet(
    *,
    type: list[_PlanetType] = ...,
    environment: list[_PlanetEnvironment] = ...,
    size: list[_PlanetSize] = ...,
    species: _SpeciesValue = ...,
) -> _Condition: ...
def Star(*, type: list[_StarType]) -> _Condition: ...
def Location(*, type: _Focus, name: _SpeciesValue, name2: _Focus | str) -> _Condition: ...
def HasSpecies(*, name: list[_StringParam] = ...) -> _Condition: ...
def IsField(*, name: list[_StringParam]) -> _Condition: ...
def Population(*, low: _FloatParam = ..., high: _FloatParam = ...) -> _Condition: ...
def Industry(*, low: _FloatParam = ..., high: _FloatParam = ...) -> _Condition: ...
def TargetPopulation(*, low: _FloatParam = ..., high: _FloatParam = ...) -> _Condition: ...
def SpeciesLikes(*, name: _Focus | _BuildingType | _SpeciesValue) -> _Condition: ...
def SpeciesDislikes(*, name: _Focus | _BuildingType | _SpeciesValue) -> _Condition: ...
def Homeworld(*, name: list[_SpeciesValue] = ...) -> _Condition: ...
def HasTag(*, name: str) -> _Condition: ...
def VisibleToEmpire(*, empire: _EmpireId) -> _Condition: ...
def ContainedBy(condition: _Condition, /) -> _Condition: ...
def HasSpecial(*, name: str) -> _Condition: ...
def OwnerHasTech(*, name: str) -> _Condition: ...

System = _Condition()
Ship = _Condition()
Monster = _Condition()
Armed = _Condition()
Unowned = _Condition()
Capital = _Condition()
IsHuman = _Condition()
Fleet = _Condition()
Stationary = _Condition()
NoOpCondition = _Condition()
IsSource = _Condition()
IsRootCandidate = _Condition()
IsTarget = _Condition()
CanColonize = _Condition()
IsAnyObject = _Condition()
CanProduceShips = _Condition()

def InGame() -> _Condition: ...
def InSystem(*, id: _SystemID = _SystemID()) -> _Condition: ...

GalaxyMaxAIAggression = 0
GalaxyMonsterFrequency = 0

def Described(*, description: str, condition: _Condition) -> _Condition: ...
def MinimumNumberOf(number: int, sortkey: _FloatParam, condition: _Condition) -> _Condition: ...
def MaximumNumberOf(number: int, sortkey: _FloatParam, condition: _Condition) -> _Condition: ...
def NumberOf(number: int, condition: _Condition) -> _Condition: ...
def UniqueNumberOf(*, number: int, condition: _Condition, sortkey) -> _Condition: ...
def TargetIndustry(*, low: float) -> _Condition: ...
def Stealth(*, high: float) -> _Condition: ...
def Speed(*, low: float) -> _Condition: ...
def Happiness(*, low: _FloatParam) -> _Condition: ...
def Focus(*, type: list[str]) -> _Condition: ...
def Random(*, probability: _FloatParam) -> _Condition: ...
def OwnedBy(*, affiliation: _EmpireId = _Empire(), empire: _EmpireId = _Empire()) -> _Condition: ...
def WithinStarlaneJumps(*, jumps: _IntParam, condition: _Condition) -> _Condition: ...
def WithinDistance(*, distance: float, condition: _Condition) -> _Condition: ...
def ResourceSupplyConnected(*, empire: _EmpireId, condition: _Condition) -> _Condition: ...
def Contains(scope: _Condition, /) -> _Condition: ...
def Turn(*, high: _FloatParam = ..., low: _FloatParam = ...) -> _Condition: ...
def Structure(*, low: _FloatParam = ..., high: _FloatParam = ...) -> _Condition: ...
def ResupplyableBy(*, empire: _EmpireId) -> _Condition: ...
def DesignHasPart(*, name: str, low: int = ..., high: int = ...) -> _Condition: ...
def EmpireHasAdoptedPolicy(*, name: str, empire: _EmpireId = _Empire()) -> _Condition: ...
def ProducedByEmpire(*, empire: _Empire) -> _Condition: ...
def HasStarlane(from_: _Condition) -> _Condition: ...
def HasDesign(name: _StringParam) -> _Condition: ...
def StarlaneToWouldCrossExistingStarlane(from_: _Condition) -> _Condition: ...
def StarlaneToWouldBeAngularlyCloseToExistingStarlane(from_: _Condition, maxdotprod: float) -> _Condition: ...
def StarlaneToWouldBeCloseToObject(*, distance: float, from_: _Condition, closeto: _Condition) -> _Condition: ...

ResourceInfluence = _Resource()
ResourceIndustry = _Resource()

def HasEmpireStockpile(*, empire: _EmpireId, resource: _Resource, low: int = ..., high: int = ...) -> _Condition: ...
def NumPoliciesAdopted(*, empire: _EmpireId) -> int: ...
def BuildingTypesProduced(*, empire: _EmpireId) -> int: ...
def BuildingTypesScrapped(*, empire: _EmpireId) -> int: ...
def ShipDesignsLost(*, empire: _EmpireId) -> int: ...
def ShipDesignsProduced(*, empire: _EmpireId) -> int: ...
def ShipDesignsScrapped(*, empire: _EmpireId) -> int: ...
def SpeciesPlanetsBombed(*, empire: _EmpireId) -> int: ...
def SpeciesPlanetsDepoped(*, empire: _EmpireId) -> int: ...
def SpeciesPlanetsInvaded(*, empire: _EmpireId) -> int: ...
def OnPlanet(*, id: _ID) -> _Condition: ...

# Effects
Destroy = _Effect()

def GameRule(
    *,
    type: type[_T],
    name: str,
) -> _T: ...

NoOpEffect = _Effect()

def Conditional(
    *,
    condition: _Condition | bool,
    effects: list[_Effect],
    else_: list[_Effect] = ...,
) -> _Effect: ...
def AddSpecial(*, name: str, capacity: _FloatParam = ...) -> _Effect: ...
def RemoveSpecial(*, name: str) -> _Effect: ...
def SetMaxShield(*, value: _FloatParam, accountinglabel: str = "") -> _Effect: ...
def SetMaxStructure(*, value: _FloatParam, accountinglabel: str = "") -> _Effect: ...
def SetEmpireStockpile(*, resource: _Resource, value: _FloatParam) -> _Effect: ...
def SetShield(*, value: _FloatParam) -> _Effect: ...
def SetTargetIndustry(*, value: _FloatParam) -> _Effect: ...
def SetDetection(*, value: _FloatParam) -> _Effect: ...
def SetStructure(*, value: _FloatParam) -> _Effect: ...
def SetFuel(*, value: _FloatParam) -> _Effect: ...
def SetDefense(*, value: _FloatParam) -> _Effect: ...
def SetMaxTroops(*, value: _FloatParam) -> _Effect: ...
def SetStockpile(*, value: _FloatParam) -> _Effect: ...
def SetMaxStockpile(*, value: _FloatParam, accountinglabel: str = "") -> _Effect: ...
def SetTargetHappiness(*, value: _FloatParam) -> _Effect: ...
def GiveEmpirePolicy(*, name: str, empire: _EmpireId = _Empire()) -> _Effect: ...
def SetVisibility(empire: _EmpireId, visibility: Any, affiliation=_Affilation()) -> _Effect: ...
def SetPopulation(*, value: _FloatParam) -> _Effect: ...
def SetPlanetType(*, type: _PlanetType) -> _Effect: ...
def SetSpeed(*, value: _FloatParam) -> _Effect: ...
def SetSpecies(*, name: _StringParam) -> _Effect: ...
def SetTroops(*, value: _FloatParam) -> _Effect: ...
def SetMaxDefense(*, value: _FloatParam) -> _Effect: ...
def SetSupply(*, value: _FloatParam) -> _Effect: ...
def SetTargetResearch(*, value: _FloatParam) -> _Effect: ...
def SetHappiness(*, value: _FloatParam) -> _Effect: ...
def SetPlanetSize(*, planetsize: _PlanetSize) -> _Effect: ...
def SetMaxSupply(*, value: _FloatParam) -> _Effect: ...
def SetMaxFuel(*, value: _FloatParam) -> _Effect: ...
def SetResearch(*, value: _FloatParam) -> _Effect: ...
def SetIndustry(*, value: _FloatParam) -> _Effect: ...
def SetInfluence(*, value: _FloatParam) -> _Effect: ...
def SetSpeciesTargetOpinion(*, species: _SpeciesValue, empire: _EmpireId, opinion: _FloatParam) -> _Effect: ...
def SetSpeciesOpinion(*, species: _SpeciesValue, empire: _EmpireId, opinion: _FloatParam) -> _Effect: ...
def SetTargetPopulation(*, value: _FloatParam, accountinglabel: str = "") -> _Effect: ...
def SetTargetInfluence(*, value: _FloatParam) -> _Effect: ...
def SetTargetConstruction(*, value: _FloatParam) -> _Effect: ...
def SetConstruction(*, value: _FloatParam) -> _Effect: ...
def SetRebelTroops(*, value: _FloatParam) -> _Effect: ...
def SetStealth(*, value: _FloatParam) -> _Effect: ...
def CreateBuilding(*, type: str) -> _Effect: ...
def CreateShip(*, designname: str, empire=_Empire(), species: str | _SpeciesValue = "") -> _Effect: ...
def SetCapacity(*, partname: str, value: _FloatParam) -> _Effect: ...
def SetSecondaryStat(*, partname: str, value: _FloatParam) -> _Effect: ...
def SetMaxDamage(*, partname: str, value: _FloatParam) -> _Effect: ...
def SetMaxCapacity(*, partname: str, value: _FloatParam) -> _Effect: ...
def SetMaxSecondaryStat(*, partname: str, value: _FloatParam) -> _Effect: ...
def MoveTo(*, destination: _Condition) -> _Effect: ...
def MoveTowards(*, speed: int, target=_Condition(), x: int = ..., y: int = ...) -> _Effect: ...
def SetStarType(*, type: _StarType) -> _Effect: ...
def SetEmpireMeter(*, empire: _EmpireId, meter: str, value: _FloatParam) -> _Effect: ...
def SetOwner(*, empire: _EmpireId) -> _Effect: ...
def SetSpecialCapacity(name: str | _SpeciesValue, capacity: _ValueParam) -> _Effect: ...
def GenerateSitRepMessage(
    *,
    NoStringtableLookup: bool = True,
    message: str,
    label: str,
    empire: _EmpireId = ...,
    parameters: dict[str, Any] = ...,
    icon: str = "",
) -> _Effect: ...
def GiveEmpireTech(*, name: str, empire: _EmpireId = _Empire()) -> _Effect: ...
def Victory(*, reason: str) -> _Effect: ...
def CreateField(*, type: _StringParam, size: _IntParam) -> _Effect: ...
def AddStarlanes(endpoint: _Condition) -> _Effect: ...
def RemoveStarlanes(endpoint: _Condition) -> _Effect: ...
def SetEmpireCapital() -> _Effect: ...
