# Module for typing checks in sceleton files
# Python do not have typing library included in FOCS parsing environment.
# See discussion here: https://github.com/freeorion/freeorion/issues/4844

try:
    from typing import Literal, TypeVar, overload

    class _Condition:
        """
        This value represent an expression that is resolved to boolean.

        We need to have a special "class" because we use integer operands with it (& | ~),
        which return int type, that breaks linter logic.
        """

        def __and__(self, other) -> _Condition: ...
        def __or__(self, other) -> _Condition: ...
        def __invert__(self) -> _Condition: ...
        def __gt__(self, other) -> _Condition: ...
        def __ge__(self, other) -> _Condition: ...
        def __lt__(self, other) -> _Condition: ...
        def __le__(self, other) -> _Condition: ...
        def __mul__(self, other) -> int:
            return 0

        def __rmul__(self, other) -> int:
            return 0

        def __eq__(self, other) -> _Condition: ...  # type: ignore[invalid-method-override]
        def __ne__(self, other) -> _Condition: ...  # type: ignore[invalid-method-override]

    class _ConditionalComposition:
        """
        Base class to type that return conditions when used in comparison operations.
        """

        def __eq__(self, other) -> _Condition: ...  # type: ignore[invalid-method-override]
        def __ne__(self, other) -> _Condition: ...  # type: ignore[invalid-method-override]
        def __lt__(self, other) -> _Condition: ...
        def __gt__(self, other) -> _Condition: ...
        def __le__(self, other) -> _Condition: ...
        def __ge__(self, other) -> _Condition: ...

    class _Int(_ConditionalComposition):
        @overload
        def __mul__(self, other: int) -> _Int: ...
        @overload
        def __mul__(self, other) -> _Float: ...
        @overload
        def __rmul__(self, other: int) -> _Int: ...
        @overload
        def __rmul__(self, other) -> _Float: ...
        def __truediv__(self, other) -> _Float: ...
        def __rtruediv__(self, other) -> _Float: ...
        def __sub__(self, other) -> _Int: ...
        def __rsub__(self, other) -> _Int: ...
        def __add__(self, other) -> _Int: ...
        def __radd__(self, other) -> _Int: ...
        def __pow__(self, other) -> _Int: ...
        def __rpow__(self, other) -> _Int: ...
        def __neg__(self) -> _Int: ...

    class _Float(_ConditionalComposition):
        def __mul__(self, other) -> _Float: ...
        def __rmul__(self, other) -> _Float: ...
        def __truediv__(self, other) -> _Float: ...
        def __rtruediv__(self, other) -> _Float: ...
        def __sub__(self, other) -> _Float: ...
        def __rsub__(self, other) -> _Float: ...
        def __add__(self, other) -> _Float: ...
        def __radd__(self, other) -> _Float: ...
        def __pow__(self, other) -> _Float: ...
        def __rpow__(self, other) -> _Float: ...
        def __neg__(self) -> _Float: ...

    class _ValuePlaceholder(_ConditionalComposition):
        def __call__(self, arg: _ValueParam) -> _T: ...
        def __add__(self, other: _T) -> _T: ...
        def __radd__(self, other: _T) -> _T: ...
        def __sub__(self, other: _T) -> _T: ...
        def __rsub__(self, other: _T) -> _T: ...
        def __mul__(self, other: _T) -> _T: ...
        def __rmul__(self, other: _T) -> _T: ...
        def __floordiv__(self, other: _T) -> _T: ...
        def __rfloordiv__(self, other: _T) -> _T: ...
        def __truediv__(self, other: _T) -> _T: ...
        def __rtruediv__(self, other: _T) -> _T: ...
        def __pow__(self, other: _T) -> _T: ...
        def __rpow__(self, other: _T) -> _T: ...

    class _MeterType: ...
    class _Effect: ...
    class _EffectGroup: ...
    class _StarType: ...
    class _Visibility: ...
    class _PlanetSize: ...
    class _PlanetType: ...
    class _PlanetEnvironment: ...
    class _ShipPartClass: ...
    class _EnqueuedObjectType: ...
    class _ItemType: ...
    class _CaptureResult: ...

    # Type for return
    class _Empire: ...
    class _Affilation(_Empire): ...

    # Type for arguments, since invalid Empire is -1
    _EmpireId = _Empire | Literal[-1]

    class _Focus: ...
    class _Resource: ...
    class _Aggregator: ...

    _T = TypeVar("_T", str, int, float)
    _N = TypeVar("_N", int, float)
    # For some generic functions like Statistic
    # we need to specify type of processed argument
    # and type of output separately
    _T_IN = TypeVar("_T_IN", str, int, float, _Int)
    _T_OUT = TypeVar("_T_OUT", str, int, float, _Int)

    _SpeciesValue = str

    # Type hints for function arguments.  This could be a literal or _Int, _Float returned by other function.
    _StringParam = str
    _IntParam = int | _Int
    # We assume that we accept int anywhere we could accept float
    _FloatParam = int | float | _Int | _Float
    _ValueParam = int | float | str | _Int | _Float

    class _ID:
        def __eq__(self, other: _IntParam | _ID) -> _Condition: ...  # type: ignore[invalid-method-override]
        def __ne__(self, other: _IntParam) -> _Condition: ...  # type: ignore[invalid-method-override]
        def __ge__(self, other: _IntParam) -> _Condition: ...

    class _FleetID(_ID): ...
    class _SystemID(_ID): ...
    class _PlanetId(_ID): ...
    class _DesignID(_ID): ...
    class _BuildingType: ...

except ModuleNotFoundError:
    pass
