from focs._types import _Empire

def EmpireShipsDestroyed(empire: _Empire) -> int: ...
def ShipDesignsLost(empire: _Empire) -> int: ...
def ShipDesignsProduced(empire: _Empire) -> int: ...
def ShipDesignsScrapped(empire: _Empire) -> int: ...
def ShipDesignsOwned(empire: _Empire) -> int: ...
def NumPartClassesInShipDesign(design: _DesignID) -> _Int: ...
def PartOfClassInShipDesign(*, name: str, design: _DesignID) -> _Int: ...
def RandomNumber(type: type[_T], min: _T, max: _T) -> _T: ...

UniverseCentreX = 0.0
UniverseCentreY = 0.0
UniverseWidth = 0.0
