from focs._types import (
    _T,
    _DesignID,
    _Empire,
    _EmpireId,
    _Int,
)

def EmpireAdoptedPolicies(*, empire: _EmpireId) -> list[str]: ...
def EmpireShipsDestroyed(empire: _Empire) -> _Int: ...
def ShipDesignsLost(empire: _Empire) -> _Int: ...
def ShipDesignsProduced(empire: _Empire) -> _Int: ...
def ShipDesignsScrapped(empire: _Empire) -> _Int: ...
def ShipDesignsOwned(empire: _Empire) -> _Int: ...
def NumPartClassesInShipDesign(design: _DesignID) -> _Int: ...
def PartOfClassInShipDesign(*, name: str, design: _DesignID) -> _Int: ...
def RandomNumber(type: type[_T], min: _T, max: _T) -> _T: ...
def VectorCount(type_: type[_T], vector_: list[str]) -> _T: ...

UniverseCentreX = 0.0
UniverseCentreY = 0.0
UniverseWidth = 0.0
