FROM docker.io/fedora:33

RUN dnf update -y
RUN dnf install -y cmake \
	ccache \
	python3-devel \
	gcc-c++ \
	git \
	boost-devel \
	boost-python3-devel \
	zlib-devel \
	SDL2-devel \
	freetype-devel \
	openal-devel \
	libogg-devel \
	libvorbis-devel \
	glew-devel \
	godot-headless

