name: 'flake8-lint'
description: 'Lint directory with the flake8'
inputs:
  directories:
    description: 'Directories to check'
    required: true
  args:
    description: 'Extra arguments'
    required: true
runs:
  using: "composite"
  steps:
    - run: >
        flake8 ${{ inputs.directories }}
        ${{ inputs.args }}
        --format="::error file=%(path)s,line=%(row)d,col=%(col)d::%(path)s:%(row)d:%(col)d: %(code)s %(text)s"
      shell: bash
