FROM docker.io/fedora:rawhide

RUN dnf5 update -y
RUN dnf5 install -y cmake \
	ccache \
	python3-devel \
	gcc-c++ \
	git \
	boost-devel \
	boost-python3-devel \
	zlib-devel \
	SDL2-devel \
	freetype-devel \
	openal-devel \
	libogg-devel \
	libvorbis-devel \
	glew-devel \
	godot3-headless

