// -*- C++ -*-
/* GG is a GUI for SDL and OpenGL.
   Copyright (C) 2003-2008 T. Zachary Laine

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public License
   as published by the Free Software Foundation; either version 2.1
   of the License, or (at your option) any later version.
   
   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.
    
   You should have received a copy of the GNU Lesser General Public
   License along with this library; if not, write to the Free
   Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
   02111-1307 USA

   If you do not wish to comply with the terms of the LGPL please
   contact the author as other terms are available for a fee.
    
   Zach Laine
   whatwasthataddress@gmail.com */

/* *** WARNING! ***
   This file is auto-generated by gen_signals.py.
   *** ALL CHANGES WILL BE LOST! *** */

#define GG_SIGNALS_NUM_ARGS 7
#define GG_SIGNALS_SIGNAL_TEMPLATE_PARMS class A1, class A2, class A3, class A4, class A5, class A6, class A7
#define GG_SIGNALS_SIGNAL_TEMPLATE_ARGS A1, A2, A3, A4, A5, A6, A7
#define GG_SIGNALS_SIGNAL_PARMS A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7
#define GG_SIGNALS_SIGNAL_ARGS a1, a2, a3, a4, a5, a6, a7
#define GG_SIGNALS_BIND_ARGS _1, _2, _3, _4, _5, _6, _7

#include "SignalTemplate.h"

#undef GG_SIGNALS_NUM_ARGS
#undef GG_SIGNALS_SIGNAL_TEMPLATE_PARMS
#undef GG_SIGNALS_SIGNAL_TEMPLATE_ARGS
#undef GG_SIGNALS_SIGNAL_PARMS
#undef GG_SIGNALS_SIGNAL_ARGS
#undef GG_SIGNALS_BIND_ARGS
