name: freeorion
base: core20
summary: turn-based space empire and galactic conquest (4X) computer game
description: |
  FreeOrion is a free, open source, turn-based space empire and galactic
  conquest (4X) computer game being designed and built by the FreeOrion project.
  FreeOrion is inspired by the tradition of the Master of Orion games, but is
  not a clone or remake of that series or any other game.
confinement: strict
adopt-info: freeorion
architectures:
  - build-on: amd64

apps:
  freeorion:
    command: usr/local/bin/freeorion -S $SNAP_USER_COMMON/save
    extensions: [gnome-3-38]
    plugs: [home, pulseaudio, opengl, network, screen-inhibit-control, browser-support, x11]
    desktop: usr/local/share/applications/org.freeorion.FreeOrion.desktop
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/local/lib/freeorion
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/x86_64-linux-gnu/dri
      #PYTHONPATH: $SNAP/usr/lib/python3.6
  freeoriond:
    command: usr/local/bin/freeoriond
    plugs: [home, network, network-bind]
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/local/lib/freeorion
      #PYTHONPATH: $SNAP/usr/lib/python3.6
  freeoriond-dedicated:
    command: usr/local/bin/freeoriond --hostless --network.server.unconn-human-empire-players.max 0 --network.server.conn-human-empire-players.min 0
    plugs: [home, network, network-bind]
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/local/lib/freeorion
      #PYTHONPATH: $SNAP/usr/lib/python3.6

parts:
  freeorion:
    source: .
    override-build: |
      sed -i.bak -e 's|Icon=freeorion$|Icon=${SNAP}/meta/gui/icon.png|g' ../src/packaging/org.freeorion.FreeOrion.desktop
      snapcraftctl build
    plugin: cmake
    #cmake-parameters: [-DBUILD_TESTING=ON]
    override-pull: |
      snapcraftctl pull
      # this versioning works for e.g. weekly-test-builds
      branchn="$(git rev-parse --abbrev-ref HEAD)"
      version="$(git log -n1 --date=short --format='%cd.%h' freeorion/$branchn)"
      case $version in
        v*) version=$(echo $version | tail -c +2) ;;
        *)  version=$(echo $version | head -c 32) ;;
      esac
      [ -n "$(echo $version | grep '-')" ] && grade=devel || grade=stable
      snapcraftctl set-version "$version"
      snapcraftctl set-grade "$grade"
    override-prime: |
      snapcraftctl prime
      mkdir -p ${SNAPCRAFT_PRIME}/meta/gui
      cp ${SNAPCRAFT_PART_SRC}/default/data/art/icons/FO_Icon_256x256.png ${SNAPCRAFT_PRIME}/meta/gui/icon.png
    build-packages:
      - cmake
      - debhelper
      - dpkg-dev
      - git
      - libalut-dev
      - libboost1.67-all-dev
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libglew-dev
      - libjpeg-dev
      - libogg-dev
      - libopenal-dev
      - libpng-dev
      - libsdl2-dev
      - libtiff-dev
      - libvorbis-dev
      - pkg-config
      #- python
    stage-packages:
      - mesa-utils
      - libgl1-mesa-dri
      #- python3
      #- libpython3.8
      - libboost-date-time1.67.0
      - libboost-filesystem1.67.0
      - libboost-iostreams1.67.0
      - libboost-locale1.67.0
      - libboost-log1.67.0
      - libboost-python1.67.0
      - libboost-regex1.67.0
      - libboost-serialization1.67.0
      - libboost-system1.67.0
      - libboost-thread1.67.0
      - libboost-test1.67.0
      - libglew2.1
      - libglu1-mesa
      - libopenal1
      - libsdl2-2.0-0
      - libvorbis0a
      - libvorbisfile3
      - libpng16-16
      - libfreetype6
