FROM docker.io/alpine:edge

RUN apk update
RUN apk add --no-cache cmake \
    make \
    build-base \
    python3-dev \
    boost-dev \
    sdl2-dev \
    freetype-dev \
    openal-soft-dev \
    glew-dev

