#include "EncyclopediaDetailPanel.h"

#include "CUIControls.h"
#include "../universe/Universe.h"
#include "../universe/Tech.h"
#include "../universe/ShipDesign.h"
#include "../universe/Building.h"
#include "../universe/Planet.h"
#include "../universe/System.h"
#include "../universe/Ship.h"
#include "../universe/Fleet.h"
#include "../universe/Special.h"
#include "../universe/Species.h"
#include "../universe/Effect.h"
#include "../Empire/Empire.h"
#include "../Empire/EmpireManager.h"
#include "../util/MultiplayerCommon.h"
#include "../util/OptionsDB.h"
#include "../client/human/HumanClientApp.h"

#include <GG/DrawUtil.h>
#include <GG/StaticGraphic.h>
#include <GG/GUI.h>

namespace {
    const GG::X TEXT_MARGIN_X(3);
    const GG::Y TEXT_MARGIN_Y(3);
    void    AddOptions(OptionsDB& db) {
        db.Add("UI.autogenerated-effects-descriptions", "OPTIONS_DB_AUTO_EFFECT_DESC",  false,  Validator<bool>());
    }
    bool temp_bool = RegisterOptions(&AddOptions);

    const std::string EMPTY_STRING;
}

namespace {
    std::string LinkTaggedText(const std::string& tag, const std::string& stringtable_entry) {
        return "<" + tag + " " + stringtable_entry + ">" + UserString(stringtable_entry) + "</" + tag + ">" + "\n";
    }

    std::string LinkTaggedIDText(const std::string& tag, int id, const std::string& text) {
        return "<" + tag + " " + boost::lexical_cast<std::string>(id) + ">" + text + "</" + tag + ">" + "\n";
    }

    std::string PediaIndexText() {
        std::string retval;

        retval += UserString("ENC_SHIP_PART") + "\n\n";
        const PartTypeManager& part_type_manager = GetPartTypeManager();
        for (PartTypeManager::iterator it = part_type_manager.begin(); it != part_type_manager.end(); ++it)
            retval += LinkTaggedText(VarText::SHIP_PART_TAG, it->first);

        retval += "\n" + UserString("ENC_SHIP_HULL") + "\n\n";
        const HullTypeManager& hull_type_manager = GetHullTypeManager();
        for (HullTypeManager::iterator it = hull_type_manager.begin(); it != hull_type_manager.end(); ++it)
            retval += LinkTaggedText(VarText::SHIP_HULL_TAG, it->first);

        retval += "\n" + UserString("ENC_TECH") + "\n\n";
        std::vector<std::string> tech_names = GetTechManager().TechNames();
        for (std::vector<std::string>::const_iterator it = tech_names.begin(); it != tech_names.end(); ++it)
            retval += LinkTaggedText(VarText::TECH_TAG, *it);

        retval += "\n" + UserString("ENC_BUILDING_TYPE") + "\n\n";
        const BuildingTypeManager& building_type_manager = GetBuildingTypeManager();
        for (BuildingTypeManager::iterator it = building_type_manager.begin(); it != building_type_manager.end(); ++it)
            retval += LinkTaggedText(VarText::BUILDING_TYPE_TAG, it->first);

        retval += "\n" + UserString("ENC_SPECIAL") + "\n\n";
        std::vector<std::string> special_names = SpecialNames();
        for (std::vector<std::string>::const_iterator it = special_names.begin(); it != special_names.end(); ++it)
            retval += LinkTaggedText(VarText::SPECIAL_TAG, *it);

        retval += "\n" + UserString("ENC_SPECIES") + "\n\n";
        const SpeciesManager& species_manager = GetSpeciesManager();
        for (SpeciesManager::iterator it = species_manager.begin(); it != species_manager.end(); ++it)
            retval += LinkTaggedText(VarText::SPECIES_TAG, it->first);

        retval += "\n" + UserString("ENC_EMPIRE") + "\n\n";
        const EmpireManager& empire_manager = Empires();
        for (EmpireManager::const_iterator it = empire_manager.begin(); it != empire_manager.end(); ++it)
            retval += LinkTaggedIDText(VarText::EMPIRE_ID_TAG, it->first, it->second->Name());

        const Universe& universe = GetUniverse();

        retval += "\n" + UserString("ENC_SHIP_DESIGN") + "\n\n";
        for (Universe::ship_design_iterator it = universe.beginShipDesigns(); it != universe.endShipDesigns(); ++it)
            retval += LinkTaggedIDText(VarText::DESIGN_ID_TAG, it->first, it->second->Name());

        return retval;
    }
}

EncyclopediaDetailPanel::EncyclopediaDetailPanel(GG::X w, GG::Y h) :
    CUIWnd("", GG::X1, GG::Y1, w - 1, h - 1, GG::ONTOP | GG::INTERACTIVE | GG::DRAGABLE | GG::RESIZABLE),
    m_tech_name(),
    m_part_name(),
    m_hull_name(),
    m_building_name(),
    m_special_name(),
    m_species_name(),
    m_design_id(ShipDesign::INVALID_DESIGN_ID),
    m_object_id(UniverseObject::INVALID_OBJECT_ID),
    m_empire_id(ALL_EMPIRES),
    m_incomplete_design(),
    m_name_text(0),
    m_cost_text(0),
    m_summary_text(0),
    m_description_box(0),
    m_icon(0),
    m_other_icon(0)
{
    const int PTS = ClientUI::Pts();
    const int NAME_PTS = PTS*3/2;
    const int COST_PTS = PTS;
    const int SUMMARY_PTS = PTS*4/3;

    m_name_text =       new GG::TextControl(GG::X0, GG::Y0, GG::X(10), GG::Y(10), "", ClientUI::GetBoldFont(NAME_PTS),  ClientUI::TextColor());
    m_cost_text =       new GG::TextControl(GG::X0, GG::Y0, GG::X(10), GG::Y(10), "", ClientUI::GetFont(COST_PTS),      ClientUI::TextColor());
    m_summary_text =    new GG::TextControl(GG::X0, GG::Y0, GG::X(10), GG::Y(10), "", ClientUI::GetFont(SUMMARY_PTS),   ClientUI::TextColor());

    CUILinkTextMultiEdit* desc_box = new CUILinkTextMultiEdit(GG::X0, GG::Y0, GG::X(10), GG::Y(10), "", GG::MULTI_WORDBREAK | GG::MULTI_READ_ONLY);
    GG::Connect(desc_box->LinkClickedSignal,        &EncyclopediaDetailPanel::HandleLinkClick,          this);
    GG::Connect(desc_box->LinkDoubleClickedSignal,  &EncyclopediaDetailPanel::HandleLinkDoubleClick,    this);
    GG::Connect(desc_box->LinkRightClickedSignal,   &EncyclopediaDetailPanel::HandleLinkDoubleClick,    this);
    m_description_box = desc_box;
    m_description_box->SetColor(GG::CLR_ZERO);
    m_description_box->SetInteriorColor(ClientUI::CtrlColor());

    AttachChild(m_name_text);
    AttachChild(m_cost_text);
    AttachChild(m_summary_text);
    AttachChild(m_description_box);

    SetChildClippingMode(ClipToClientAndWindowSeparately);

    DoLayout();
}

void EncyclopediaDetailPanel::DoLayout() {
    const int PTS = ClientUI::Pts();
    const int NAME_PTS = PTS*3/2;
    const int COST_PTS = PTS;
    const int SUMMARY_PTS = PTS*4/3;

    const int ICON_SIZE = 12 + NAME_PTS + COST_PTS + SUMMARY_PTS;

    // name
    GG::Pt ul = GG::Pt();
    GG::Pt lr = ul + GG::Pt(Width(), GG::Y(NAME_PTS + 4));
    m_name_text->SizeMove(ul, lr);

    // cost / turns
    ul += GG::Pt(GG::X0, m_name_text->Height());
    lr = ul + GG::Pt(Width(), GG::Y(COST_PTS + 4));
    m_cost_text->SizeMove(ul, lr);

    // one line summary
    ul += GG::Pt(GG::X0, m_cost_text->Height());
    lr = ul + GG::Pt(Width(), GG::Y(SUMMARY_PTS + 4));
    m_summary_text->SizeMove(ul, lr);

    // main verbose description (fluff, effects, unlocks, ...)
    ul = GG::Pt(BORDER_LEFT, ICON_SIZE + TEXT_MARGIN_Y + 1);
    lr = GG::Pt(Width() - BORDER_RIGHT, Height() - BORDER_BOTTOM*3);
    m_description_box->SizeMove(ul, lr);

    // icon
    if (m_icon) {
        ul = GG::Pt(GG::X1, GG::Y1);
        lr = ul + GG::Pt(GG::X(ICON_SIZE), GG::Y(ICON_SIZE));
        m_icon->SizeMove(ul, lr);
    }
    // other icon
    if (m_other_icon) {
        lr = GG::Pt(Width() - BORDER_RIGHT, GG::Y(ICON_SIZE + 1));
        ul = lr - GG::Pt(GG::X(ICON_SIZE), GG::Y(ICON_SIZE));
        m_other_icon->SizeMove(ul, lr);
    }
}

void EncyclopediaDetailPanel::SizeMove(const GG::Pt& ul, const GG::Pt& lr) {
    GG::Pt old_size = GG::Wnd::Size();

    // maybe later do something interesting with docking
    GG::Wnd::SizeMove(ul, lr);

    if (Visible() && old_size != GG::Wnd::Size())
        DoLayout();
}

GG::Pt EncyclopediaDetailPanel::ClientUpperLeft() const {
    return GG::Wnd::UpperLeft();
}

void EncyclopediaDetailPanel::Render() {
    GG::Pt ul = UpperLeft();
    GG::Pt lr = LowerRight();
    const GG::Y ICON_SIZE = m_summary_text->LowerRight().y - m_name_text->UpperLeft().y;
    GG::Pt cl_ul = ul + GG::Pt(BORDER_LEFT, ICON_SIZE + BORDER_BOTTOM); // BORDER_BOTTOM is the size of the border at the bottom of a standard CUIWnd
    GG::Pt cl_lr = lr - GG::Pt(BORDER_RIGHT, BORDER_BOTTOM);

   // use GL to draw the lines
    glDisable(GL_TEXTURE_2D);
    GLint initial_modes[2];
    glGetIntegerv(GL_POLYGON_MODE, initial_modes);

    // draw background
    glPolygonMode(GL_BACK, GL_FILL);
    glBegin(GL_POLYGON);
        glColor(ClientUI::WndColor());
        glVertex(ul.x, ul.y);
        glVertex(lr.x, ul.y);
        glVertex(lr.x, lr.y - OUTER_EDGE_ANGLE_OFFSET);
        glVertex(lr.x - OUTER_EDGE_ANGLE_OFFSET, lr.y);
        glVertex(ul.x, lr.y);
        glVertex(ul.x, ul.y);
    glEnd();

    // draw outer border on pixel inside of the outer edge of the window
    glPolygonMode(GL_BACK, GL_LINE);
    glBegin(GL_POLYGON);
        glColor(ClientUI::WndOuterBorderColor());
        glVertex(ul.x, ul.y);
        glVertex(lr.x, ul.y);
        glVertex(lr.x, lr.y - OUTER_EDGE_ANGLE_OFFSET);
        glVertex(lr.x - OUTER_EDGE_ANGLE_OFFSET, lr.y);
        glVertex(ul.x, lr.y);
        glVertex(ul.x, ul.y);
    glEnd();

    // reset this to whatever it was initially
    glPolygonMode(GL_BACK, initial_modes[1]);

    // draw inner border, including extra resize-tab lines
    glBegin(GL_LINE_STRIP);
        glColor(ClientUI::WndInnerBorderColor());
        glVertex(cl_ul.x, cl_ul.y);
        glVertex(cl_lr.x, cl_ul.y);
        glVertex(cl_lr.x, cl_lr.y - INNER_BORDER_ANGLE_OFFSET);
        glVertex(cl_lr.x - INNER_BORDER_ANGLE_OFFSET, cl_lr.y);
        glVertex(cl_ul.x, cl_lr.y);
        glVertex(cl_ul.x, cl_ul.y);
    glEnd();
    glBegin(GL_LINES);
        // draw the extra lines of the resize tab
        glColor(ClientUI::WndInnerBorderColor());
        glVertex(cl_lr.x, cl_lr.y - RESIZE_HASHMARK1_OFFSET);
        glVertex(cl_lr.x - RESIZE_HASHMARK1_OFFSET, cl_lr.y);

        glVertex(cl_lr.x, cl_lr.y - RESIZE_HASHMARK2_OFFSET);
        glVertex(cl_lr.x - RESIZE_HASHMARK2_OFFSET, cl_lr.y);
    glEnd();
    glEnable(GL_TEXTURE_2D);
}

void EncyclopediaDetailPanel::LDrag(const GG::Pt& pt, const GG::Pt& move, GG::Flags<GG::ModKey> mod_keys) {
    if (m_drag_offset != GG::Pt(-GG::X1, -GG::Y1)) {  // resize-dragging
        GG::Pt new_lr = pt - m_drag_offset;

        // constrain to within parent
        if (GG::Wnd* parent = Parent()) {
            GG::Pt max_lr = parent->ClientLowerRight();
            new_lr.x = std::min(new_lr.x, max_lr.x);
            new_lr.y = std::min(new_lr.y, max_lr.y);
        }

        Resize(new_lr - UpperLeft());
    } else {    // normal-dragging
        GG::Pt final_move = move;

        if (GG::Wnd* parent = Parent()) {
            GG::Pt ul = UpperLeft(), lr = LowerRight();
            GG::Pt new_ul = ul + move, new_lr = lr + move;

            GG::Pt min_ul = parent->ClientUpperLeft() + GG::Pt(GG::X1, GG::Y1);
            GG::Pt max_lr = parent->ClientLowerRight();
            GG::Pt max_ul = max_lr - Size();

            new_ul.x = std::max(min_ul.x, std::min(max_ul.x, new_ul.x));
            new_ul.y = std::max(min_ul.y, std::min(max_ul.y, new_ul.y));

            final_move = new_ul - ul;
        }

        GG::Wnd::LDrag(pt, final_move, mod_keys);
    }
}

bool EncyclopediaDetailPanel::NothingSet() const {
    return (m_generic_text.empty() &&
            m_part_name.empty() &&
            m_hull_name.empty() &&
            m_tech_name.empty() &&
            m_building_name.empty() &&
            m_special_name.empty() &&
            m_species_name.empty() &&
            m_incomplete_design.expired() &&
            m_design_id == ShipDesign::INVALID_DESIGN_ID &&
            m_object_id == UniverseObject::INVALID_OBJECT_ID &&
            m_empire_id == ALL_EMPIRES
            );
}

void EncyclopediaDetailPanel::HandleLinkClick(const std::string& link_type, const std::string& data) {
    using boost::lexical_cast;
    try {

        if (link_type == VarText::PLANET_ID_TAG ||
            link_type == VarText::SYSTEM_ID_TAG ||
            link_type == VarText::FLEET_ID_TAG  ||
            link_type == VarText::SHIP_ID_TAG ||
            link_type == VarText::BUILDING_ID_TAG)
        {
            this->SetObject(lexical_cast<int>(data));

        } else if (link_type == VarText::EMPIRE_ID_TAG) {
            this->SetEmpire(lexical_cast<int>(data));
        } else if (link_type == VarText::DESIGN_ID_TAG) {
            this->SetDesign(lexical_cast<int>(data));

        } else if (link_type == VarText::TECH_TAG) {
            this->SetTech(data);
        } else if (link_type == VarText::BUILDING_TYPE_TAG) {
            this->SetBuildingType(data);
        } else if (link_type == VarText::SPECIAL_TAG) {
            this->SetSpecial(data);
        } else if (link_type == VarText::SHIP_HULL_TAG) {
            this->SetHullType(data);
        } else if (link_type == VarText::SHIP_PART_TAG) {
            this->SetPartType(data);
        } else if (link_type == VarText::SPECIES_TAG) {
            this->SetSpecies(data);

        } else if (link_type == TextLinker::ENCYCLOPEDIA_TAG) {
            this->SetText(data);
        }
    } catch (const boost::bad_lexical_cast&) {
        Logger().errorStream() << "EncyclopediaDetailPanel::HandleLinkClick caught lexical cast exception for link type: " << link_type << " and data: " << data;
    }
}

void EncyclopediaDetailPanel::HandleLinkDoubleClick(const std::string& link_type, const std::string& data) {
    using boost::lexical_cast;
    try {
        if (link_type == VarText::PLANET_ID_TAG) {
            ClientUI::GetClientUI()->ZoomToPlanet(lexical_cast<int>(data));
        } else if (link_type == VarText::SYSTEM_ID_TAG) {
            ClientUI::GetClientUI()->ZoomToSystem(lexical_cast<int>(data));
        } else if (link_type == VarText::FLEET_ID_TAG) {
            ClientUI::GetClientUI()->ZoomToFleet(lexical_cast<int>(data));
        } else if (link_type == VarText::SHIP_ID_TAG) {
            ClientUI::GetClientUI()->ZoomToShip(lexical_cast<int>(data));
        } else if (link_type == VarText::BUILDING_ID_TAG) {
            ClientUI::GetClientUI()->ZoomToBuilding(lexical_cast<int>(data));

        } else if (link_type == VarText::EMPIRE_ID_TAG) {
            ClientUI::GetClientUI()->ZoomToEmpire(lexical_cast<int>(data));
        } else if (link_type == VarText::DESIGN_ID_TAG) {
            ClientUI::GetClientUI()->ZoomToShipDesign(lexical_cast<int>(data));

        } else if (link_type == VarText::TECH_TAG) {
            ClientUI::GetClientUI()->ZoomToTech(data);
        } else if (link_type == VarText::BUILDING_TYPE_TAG) {
            ClientUI::GetClientUI()->ZoomToBuildingType(data);
        } else if (link_type == VarText::SPECIAL_TAG) {
            ClientUI::GetClientUI()->ZoomToSpecial(data);
        } else if (link_type == VarText::SHIP_HULL_TAG) {
            ClientUI::GetClientUI()->ZoomToShipHull(data);
        } else if (link_type == VarText::SHIP_PART_TAG) {
            ClientUI::GetClientUI()->ZoomToShipPart(data);
        } else if (link_type == VarText::SPECIES_TAG) {
            ClientUI::GetClientUI()->ZoomToSpecies(data);

        } else if (link_type == TextLinker::ENCYCLOPEDIA_TAG) {
            this->SetText(data);
        }
    } catch (const boost::bad_lexical_cast&) {
        Logger().errorStream() << "EncyclopediaDetailPanel::HandleLinkDoubleClick caught lexical cast exception for link type: " << link_type << " and data: " << data;
    }
}

void EncyclopediaDetailPanel::Refresh() {
    if (m_icon) {
        DeleteChild(m_icon);
        m_icon = 0;
    }
    if (m_other_icon) {
        DeleteChild(m_other_icon);
        m_other_icon = 0;
    }
    m_name_text->Clear();
    m_summary_text->Clear();
    m_cost_text->Clear();
    m_description_box->Clear();

    // get details of item as applicable in order to set summary, cost, description TextControls
    std::string name = "";
    boost::shared_ptr<GG::Texture> texture;
    boost::shared_ptr<GG::Texture> other_texture;
    int turns = -1;
    double cost = 0.0;
    std::string cost_units;             // "PP" or "RP" or empty string, depending on whether and what something costs
    std::string general_type;           // general type of thing being shown, eg. "Building" or "Ship Part"
    std::string specific_type;          // specific type of thing; thing's purpose.  eg. "Farming" or "Colonization".  May be left blank for things without specific types (eg. specials)
    std::string detailed_description;
    GG::Clr color(GG::CLR_ZERO);

    using boost::io::str;
    if (!m_generic_text.empty()) {
        // plain text... not associated with any specific bit of content or in-game object
        detailed_description = m_generic_text;

    } else if (!m_part_name.empty()) {
        const PartType* part = GetPartType(m_part_name);
        if (!part) {
            Logger().errorStream() << "EncyclopediaDetailPanel::Refresh couldn't find part with name " << m_part_name;
            return;
        }

        // Ship Parts
        name = UserString(m_part_name);
        texture = ClientUI::PartTexture(m_part_name);
        turns = part->ProductionTime();
        cost = part->ProductionCost();
        cost_units = UserString("ENC_PP");
        general_type = UserString("ENC_SHIP_PART");
        specific_type = UserString(boost::lexical_cast<std::string>(part->Class()));

        detailed_description = UserString(part->Description()) + "\n\n" + part->StatDescription();
        if (GetOptionsDB().Get<bool>("UI.autogenerated-effects-descriptions") && !part->Effects().empty()) {
            detailed_description += str(FlexibleFormat(UserString("ENC_EFFECTS_STR")) % EffectsDescription(part->Effects()));
        }

    } else if (!m_hull_name.empty()) {
        const HullType* hull = GetHullType(m_hull_name);
        if (!hull) {
            Logger().errorStream() << "EncyclopediaDetailPanel::Refresh couldn't find hull with name " << m_hull_name;
            return;
        }

        // Ship Hulls
        name = UserString(m_hull_name);
        texture = ClientUI::HullTexture(m_hull_name);
        turns = hull->ProductionTime();
        cost = hull->ProductionCost();
        cost_units = UserString("ENC_PP");
        general_type = UserString("ENC_SHIP_HULL");
        // hulls have no specific types

        detailed_description = UserString(hull->Description()) + "\n\n" + hull->StatDescription();
        if (GetOptionsDB().Get<bool>("UI.autogenerated-effects-descriptions") && !hull->Effects().empty()) {
            detailed_description += str(FlexibleFormat(UserString("ENC_EFFECTS_STR")) % EffectsDescription(hull->Effects()));
        }

    } else if (!m_tech_name.empty()) {
        const Tech* tech = GetTech(m_tech_name);
        if (!tech) {
            Logger().errorStream() << "EncyclopediaDetailPanel::Refresh couldn't find tech with name " << m_tech_name;
            return;
        }

        // Technologies
        name = UserString(m_tech_name);
        texture = ClientUI::TechTexture(m_tech_name);
        other_texture = ClientUI::CategoryIcon(tech->Category()); 
        color = ClientUI::CategoryColor(tech->Category());
        turns = tech->ResearchTime();
        cost = tech->ResearchCost();
        cost_units = UserString("ENC_RP");
        general_type = str(FlexibleFormat(UserString("ENC_TECH_DETAIL_TYPE_STR"))
            % UserString(tech->Category())
            % UserString(boost::lexical_cast<std::string>(tech->Type()))
            % UserString(tech->ShortDescription()));

        detailed_description = UserString(tech->Description());
        if (GetOptionsDB().Get<bool>("UI.autogenerated-effects-descriptions") && !tech->Effects().empty()) {
            detailed_description += str(FlexibleFormat(UserString("ENC_EFFECTS_STR")) % EffectsDescription(tech->Effects()));
        }

        const std::vector<ItemSpec>& unlocked_items = tech->UnlockedItems();
        if (!unlocked_items.empty()) {
            detailed_description += UserString("ENC_TECH_DETAIL_UNLOCKS_SECTION_STR");
            for (unsigned int i = 0; i < unlocked_items.size(); ++i) {
                const ItemSpec& item = unlocked_items[i];

                std::string TAG;
                switch (item.type) {
                case UIT_BUILDING:  TAG = VarText::BUILDING_TYPE_TAG;   break;
                case UIT_SHIP_PART: TAG = VarText::SHIP_PART_TAG;       break;
                case UIT_SHIP_HULL: TAG = VarText::SHIP_HULL_TAG;       break;
                case UIT_TECH:      TAG = VarText::TECH_TAG;            break;
                }

                std::string link_text;
                if (!TAG.empty()) {
                    link_text = "<" + TAG + " " + item.name + ">"
                                + UserString(item.name)
                                + "</" + TAG + ">";
                } else {
                    link_text = UserString(item.name);
                }

                detailed_description += str(FlexibleFormat(UserString("ENC_TECH_DETAIL_UNLOCKED_ITEM_STR"))
                    % UserString(boost::lexical_cast<std::string>(unlocked_items[i].type))
                    % link_text);
            }
        }

    } else if (!m_building_name.empty()) {
        const BuildingType* building_type = GetBuildingType(m_building_name);
        if (!building_type) {
            Logger().errorStream() << "EncyclopediaDetailPanel::Refresh couldn't find building type with name " << m_building_name;
            return;
        }

        // Buildings
        name = UserString(m_building_name);
        texture = ClientUI::BuildingTexture(m_building_name);
        turns = building_type->ProductionTime();
        cost = building_type->ProductionCost();
        cost_units = UserString("ENC_PP");
        general_type = UserString("ENC_BUILDING_TYPE");

        detailed_description = UserString(building_type->Description());
        if (GetOptionsDB().Get<bool>("UI.autogenerated-effects-descriptions") && !building_type->Effects().empty()) {
            detailed_description += str(FlexibleFormat(UserString("ENC_EFFECTS_STR")) % EffectsDescription(building_type->Effects()));
        }

    } else if (!m_special_name.empty()) {
        const Special* special = GetSpecial(m_special_name);
        if (!special) {
            Logger().errorStream() << "EncyclopediaDetailPanel::Refresh couldn't find special with name " << m_special_name;
            return;
        }

        // Specials
        name = UserString(m_special_name);
        texture = ClientUI::SpecialTexture(m_special_name);
        detailed_description = UserString(special->Description());
        if (GetOptionsDB().Get<bool>("UI.autogenerated-effects-descriptions") && !special->Effects().empty()) {
            detailed_description += str(FlexibleFormat(UserString("ENC_EFFECTS_STR")) % EffectsDescription(special->Effects()));
        }

    } else if (!m_species_name.empty()) {
        const Species* species = GetSpecies(m_species_name);
        if (!species) {
            Logger().errorStream() << "EncyclopediaDetailPanel::Refresh couldn't find species with name " << m_species_name;
            return;
        }

        // Species
        name = UserString(m_species_name);
        texture = ClientUI::SpeciesIcon(m_species_name);
        general_type = UserString("ENC_SPECIES");

        detailed_description = UserString(species->Description());
        if (GetOptionsDB().Get<bool>("UI.autogenerated-effects-descriptions") && !species->Effects().empty()) {
            detailed_description += str(FlexibleFormat(UserString("ENC_EFFECTS_STR")) % EffectsDescription(species->Effects()));
        }

    } else if (boost::shared_ptr<const ShipDesign> incomplete_design = m_incomplete_design.lock()) {
        // incomplete design.  not yet in game universe; being created on design screen

        name = incomplete_design->Name();

        texture = ClientUI::GetTexture(ClientUI::ArtDir() / incomplete_design->Graphic(), true);
        if (!texture) {
            if (const HullType* hull_type = incomplete_design->GetHull())
                texture = ClientUI::HullTexture(hull_type->Name());
        } else {
            texture = ClientUI::HullTexture("");
        }

        general_type = UserString("ENC_INCOMPETE_SHIP_DESIGN");
        turns = incomplete_design->ProductionTime();
        cost = incomplete_design->ProductionCost();
        cost_units = UserString("ENC_PP");

        detailed_description = str(FlexibleFormat(UserString("ENC_SHIP_DESIGN_DESCRIPTION_STR"))
            % incomplete_design->Description()
            % static_cast<int>(incomplete_design->SRWeapons().size())
            % static_cast<int>(incomplete_design->LRWeapons().size())
            % static_cast<int>(incomplete_design->FWeapons().size())
            % static_cast<int>(incomplete_design->PDWeapons().size())
            % incomplete_design->Structure()
            % incomplete_design->Shields()
            % incomplete_design->Detection()
            % incomplete_design->BattleSpeed()
            % incomplete_design->StarlaneSpeed()
            % incomplete_design->Fuel()
            % incomplete_design->ColonyCapacity()
            % incomplete_design->Stealth());

    } else if (m_design_id != ShipDesign::INVALID_DESIGN_ID) {
        const ShipDesign* design = GetShipDesign(m_design_id);
        if (!design) {
            Logger().errorStream() << "EncyclopediaDetailPanel::Refresh couldn't find ShipDesign with id " << m_design_id;
            return;
        }

        // Ship Designs
        name = design->Name();
        texture = ClientUI::ShipIcon(design->ID());
        turns = design->ProductionTime();
        cost = design->ProductionCost();
        cost_units = UserString("ENC_PP");
        general_type = UserString("ENC_SHIP_DESIGN");
        detailed_description = str(FlexibleFormat(UserString("ENC_SHIP_DESIGN_DESCRIPTION_STR"))
            % design->Description()
            % static_cast<int>(design->SRWeapons().size())
            % static_cast<int>(design->LRWeapons().size())
            % static_cast<int>(design->FWeapons().size())
            % static_cast<int>(design->PDWeapons().size())
            % design->Structure()
            % design->Shields()
            % design->Detection()
            % design->BattleSpeed()
            % design->StarlaneSpeed()
            % design->Fuel()
            % design->ColonyCapacity()
            % design->Stealth());

    } else if (m_object_id != UniverseObject::INVALID_OBJECT_ID) {
        const UniverseObject* obj = GetUniverse().Objects().Object(m_object_id);
        if (!obj) {
            int empire_id = HumanClientApp::GetApp()->EmpireID();
            if (empire_id == ALL_EMPIRES) {
                Logger().errorStream() << "EncyclopediaDetailPanel::Refresh got invalid client's empire id.";
                return;
            }

            obj = GetUniverse().EmpireKnownObjects(empire_id).Object(m_object_id);
        }
        if (!obj) {
            Logger().errorStream() << "EncyclopediaDetailPanel::Refresh couldn't find UniverseObject with id " << m_object_id;
            return;
        }
        // UniverseObject

        if (const Ship* ship = universe_object_cast<const Ship*>(obj)) {
            name = ship->Name();
            general_type = UserString("ENC_SHIP");

        } else if (const Fleet* fleet = universe_object_cast<const Fleet*>(obj)) {
            name = fleet->Name();
            general_type = UserString("ENC_FLEET");

        } else if (const Planet* planet = universe_object_cast<const Planet*>(obj)) {
            name = planet->Name();
            general_type = UserString("ENC_PLANET");

        } else if (const Building* building = universe_object_cast<const Building*>(obj)) {
            name = building->Name();
            general_type = UserString("ENC_BUILDING");

        } else if (const System* system = universe_object_cast<const System*>(obj)) {
            name = system->Name();
            general_type = UserString("ENC_SYSTEM");

        } else {
            Logger().errorStream() << "EncyclopediaDetailPanel::Refresh couldn't interpret object: " << obj->Name() << " (" << m_object_id << ")";
            return;
        }

    } else if (m_empire_id != ALL_EMPIRES) {
        const Empire* empire = Empires().Lookup(m_empire_id);
        if (!empire) {
            Logger().errorStream() << "EncyclopediaDetailPanel::Refresh couldn't find Empire with id " << m_empire_id;
            return;
        }

        name = empire->Name();
        general_type = UserString("ENC_SHIP");
    } else {
        // apparently nothing set.  show index.
        name = UserString("ENC_INDEX");
        detailed_description = PediaIndexText();
    }

    // Create Icons
    if (texture) {
        m_icon =        new GG::StaticGraphic(GG::X0, GG::Y0, GG::X(10), GG::Y(10), texture,        GG::GRAPHIC_FITGRAPHIC | GG::GRAPHIC_PROPSCALE);
        if (color != GG::CLR_ZERO)
            m_icon->SetColor(color);
    }
    if (other_texture) {
        m_other_icon =  new GG::StaticGraphic(GG::X0, GG::Y0, GG::X(10), GG::Y(10), other_texture,  GG::GRAPHIC_FITGRAPHIC | GG::GRAPHIC_PROPSCALE);
        if (color != GG::CLR_ZERO)
            m_other_icon->SetColor(color);
    }

    if (m_icon) {
        m_icon->Show();
        AttachChild(m_icon);
    }
    if (m_other_icon) {
        m_other_icon->Show();
        AttachChild(m_other_icon);
    }

    // Set Text
    if (!name.empty())
        m_name_text->SetText(name);

    if (!specific_type.empty())
        m_summary_text->SetText(str(FlexibleFormat(UserString("ENC_DETAIL_TYPE_STR"))
            % specific_type
            % general_type));
    if (color != GG::CLR_ZERO)
        m_summary_text->SetColor(color);

    if (cost != 0.0 && turns != -1) {
        m_cost_text->SetText(str(FlexibleFormat(UserString("ENC_COST_AND_TURNS_STR"))
            % DoubleToString(cost, 4, false)
            % cost_units
            % turns));
    }

    if (!detailed_description.empty())
        m_description_box->SetText(detailed_description);

    DoLayout();
}

void EncyclopediaDetailPanel::UnsetAll() {
    m_generic_text.clear();
    m_tech_name.clear();
    m_part_name.clear();
    m_hull_name.clear();
    m_building_name.clear();
    m_special_name.clear();
    m_species_name.clear();
    m_design_id = ShipDesign::INVALID_DESIGN_ID;
    m_object_id = UniverseObject::INVALID_OBJECT_ID;
    m_empire_id = ALL_EMPIRES;
    m_incomplete_design.reset();
}

void EncyclopediaDetailPanel::SetText(const std::string& text, bool lookup_in_stringtable)
{
    if (text == m_generic_text)
        return;
    UnsetAll();
    m_generic_text = (text.empty() || !lookup_in_stringtable) ? text : UserString(text);
    Refresh();
}

void EncyclopediaDetailPanel::SetTech(const std::string& tech_name) {
    if (tech_name == m_tech_name)
        return;
    UnsetAll();
    m_tech_name = tech_name;
    Refresh();
}

void EncyclopediaDetailPanel::SetPartType(const std::string& part_name) {
    if (part_name == m_part_name)
        return;
    UnsetAll();
    m_part_name = part_name;
    Refresh();
}

void EncyclopediaDetailPanel::SetHullType(const std::string& hull_name) {
    if (hull_name == m_hull_name)
        return;
    UnsetAll();
    m_hull_name = hull_name;
    Refresh();
}

void EncyclopediaDetailPanel::SetBuildingType(const std::string& building_name) {
    if (building_name == m_building_name)
        return;
    UnsetAll();
    m_building_name = building_name;
    Refresh();
}

void EncyclopediaDetailPanel::SetSpecial(const std::string& special_name) {
    if (special_name == m_special_name)
        return;
    UnsetAll();
    m_special_name = special_name;
    Refresh();
}

void EncyclopediaDetailPanel::SetSpecies(const std::string& species_name) {
    if (species_name == m_species_name)
        return;
    UnsetAll();
    m_species_name = species_name;
    Refresh();
}

void EncyclopediaDetailPanel::SetObject(int object_id) {
    if (object_id == m_object_id)
        return;
    UnsetAll();
    m_object_id = object_id;
    Refresh();
}

void EncyclopediaDetailPanel::SetEmpire(int empire_id) {
    if (empire_id == m_empire_id)
        return;
    UnsetAll();
    m_empire_id = empire_id;
    Refresh();
}

void EncyclopediaDetailPanel::SetDesign(int design_id) {
    if (design_id == m_design_id)
        return;
    UnsetAll();
    m_design_id = design_id;
    Refresh();
}

void EncyclopediaDetailPanel::SetIncompleteDesign(boost::weak_ptr<const ShipDesign> incomplete_design) {
    UnsetAll();
    m_incomplete_design = incomplete_design;
    Refresh();
}

void EncyclopediaDetailPanel::SetItem(const Tech* tech) {
    SetTech(tech ? tech->Name() : EMPTY_STRING);
}

void EncyclopediaDetailPanel::SetItem(const PartType* part) {
    SetPartType(part ? part->Name() : EMPTY_STRING);
}

void EncyclopediaDetailPanel::SetItem(const HullType* hull_type) {
    SetHullType(hull_type ? hull_type->Name() : EMPTY_STRING);
}

void EncyclopediaDetailPanel::SetItem(const BuildingType* building_type) {
    SetBuildingType(building_type ? building_type->Name() : EMPTY_STRING);
}

void EncyclopediaDetailPanel::SetItem(const Special* special) {
    SetSpecial(special ? special->Name() : EMPTY_STRING);
}

void EncyclopediaDetailPanel::SetItem(const Species* species) {
    SetSpecies(species ? species->Name() : EMPTY_STRING);
}

void EncyclopediaDetailPanel::SetItem(const UniverseObject* obj) {
    SetObject(obj ? obj->ID() : UniverseObject::INVALID_OBJECT_ID);
}

void EncyclopediaDetailPanel::SetItem(const Empire* empire) {
    SetEmpire(empire ? empire->EmpireID() : ALL_EMPIRES);
}

void EncyclopediaDetailPanel::SetItem(const ShipDesign* design) {
    SetDesign(design ? design->ID() : ShipDesign::INVALID_DESIGN_ID);
}
