name: "Windows"

on:
  workflow_call:
jobs:
  windows-2026-cmake:
    name: MSVS 2026 on Windows CMake
    runs-on: windows-2025-vs2026
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Download SDK
        id: download-sdk
        uses: suisei-cn/actions-download-file@v1.6.1
        with:
          url: https://github.com/freeorion/freeorion-sdk/releases/download/v19/FreeOrionSDK_19_MSVC-v143-x64.zip
          target: ../
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3
        with:
          vs-prerelease: true
      - name: Configure
        shell: pwsh
        run: |
          Remove-Item -LiteralPath "C:/hostedtoolcache/windows/Python/" -Force -Recurse # Ensure that system Python is not used
          unzip -q ../${{ steps.download-sdk.outputs.filename }} -d ..
          mkdir build
          pushd build
          cmake -G "Visual Studio 18 2026" -T "v143" -A x64 -DBUILD_TESTING=On -DBUILD_CLIENT_GG=On -DBUILD_CLIENT_GODOT=4 -DCMAKE_C_FLAGS=/MP -DCMAKE_CXX_FLAGS=/MP ..
      - name: Build
        shell: pwsh
        run: |
          pushd build
          cmake --build . --config "Release" -- /maxcpucount /property:BuildInParallel=true /property:CL_MPCount=2 /verbosity:minimal
      - name: Download Godot
        id: download-godot
        uses: suisei-cn/actions-download-file@v1.6.1
        with:
          url: https://downloads.godotengine.org/?version=4.4.1&flavor=stable&slug=win64.exe.zip&platform=windows.64
          target: ../
          filename: Godot_v4.4.1-stable_win64.exe.zip
      - name: Install Godot
        shell: pwsh
        run: |
          unzip -q ../${{ steps.download-godot.outputs.filename }} -d build/Release
      - name: Test Godot
        shell: pwsh
        run: |
          $env:Path += ";$($pwd.Path)\\build\\Release"
          write-host "::group::Import"
          .\build\Release\Godot_v4.4.1-stable_win64_console.exe --headless --import --path godot4
          write-host "::endgroup::"
          write-host "::group::Test"
          .\build\Release\Godot_v4.4.1-stable_win64_console.exe --headless --verbose -s --path godot4 addons/gut/gut_cmdln.gd -gdir=res://test/ -ginclude_subdirs -gexit
          write-host "::endgroup::"
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: windows-test-logs-${{ github.run_number }}
          path: C:\Users\runneradmin\AppData\Roaming\FreeOrion\*.log
          if-no-files-found: error
          retention-days: 1
      - name: Generate binaries only
        run: |
          pushd build
          cpack -V -C Release -G ZIP -D CPACK_ARCHIVE_COMPONENT_INSTALL=ON -D CPACK_MONOLITHIC_INSTALL=OFF -D "CPACK_COMPONENTS_ALL=binaries;binaries-test"
      - name: Upload binaries artifacts
        uses: actions/upload-artifact@v7
        with:
          name: weekly-artifacts-sf-windows-${{ github.run_number }}
          path: build/FreeOrion_*.zip
          if-no-files-found: error
          retention-days: 1
