name: "Snapcraft"

on:
  workflow_call:

jobs:
  snapcraft:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build snap package
      uses: snapcore/action-build@v1
      id: snapcraft
    - name: Install built snap package
      run: |
        sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
    - name: Install dependencies for test launch
      run: |
        sudo apt update -y
        sudo apt install -y mesa-utils libgl1-mesa-dri libglx-mesa0
    - name: Test freeorion launch
      uses: coactions/setup-xvfb@v1
      with:
        run: /bin/bash .github/snap-xvfb-launch.sh

