name: "Snapcraft"

on:
  workflow_call:
    inputs:
      weekly-deploy:
        type: boolean
        default: false
    outputs:
      snap:
        description: "Snap file"
        value: ${{ jobs.snapcraft.outputs.snap }}

jobs:
  snapcraft:
    runs-on: ubuntu-latest
    timeout-minutes: 55
    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build snap package
      uses: snapcore/action-build@v1
      id: snapcraft
    - name: Install built snap package
      run: |
        sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
    - name: Install dependencies for test launch
      run: |
        sudo apt update -y
        sudo apt install -y mesa-utils libgl1-mesa-dri libglx-mesa0 imagemagick xvfb x11-xserver-utils optipng
    - name: Test freeorion launch
      run: |
        xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" /bin/bash .github/snap-xvfb-launch.sh
    - name: Optimize screenshot
      run: optipng -o2 screenshot.png
    - name: Upload logs and screenshot
      uses: actions/upload-artifact@v4
      with:
        name: snap-log-screenshot-${{ github.run_number }}
        path: |
          screenshot.png
          freeorion.log
          freeorion-godot.log
        retention-days: 1
    - name: Upload binaries artifacts
      uses: actions/upload-artifact@v4
      if: ${{ inputs.weekly-deploy }}
      with:
        name: weekly-artifacts-snap-${{ github.run_number }}
        path: ${{ steps.snapcraft.outputs.snap }}
        if-no-files-found: error
        retention-days: 1

