name: "Build"
on:
  push:
    branches: [ 'master' ]
    paths-ignore:
      - 'msvc*/**'
      - 'check/**'
      - 'doc/**'
      - 'packaging/**'
      - 'snap/**'
      - '*.md'
      - 'check/**'
      - 'default/**'
      - 'test-scripting/**'

jobs:
  build:
    uses: ./.github/workflows/_build-all.yml
  publish_weekly-release:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/_merge_to_weekly_release.yml
    needs: [ build ]
