name: "Build on scripts"
on:
  pull_request:
    branches: [ 'master' ]
    types: ['opened', 'reopened', 'synchronize']
jobs:
  detect_changed_files:
    runs-on: ubuntu-latest
    outputs:
      build_windows_cmake: ${{ steps.detect_changed_files.outputs.BUILD_WINDOWS_WITH_CMAKE }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - id: set_files_changed
        working-directory: check
        run: python check_changed_files.py
  windows:
    needs: detect_changed_files
    if: ${{ needs.detect_changed_files.outputs.build_windows_cmake == true }}
    uses: ./.github/workflows/_build-windows.yml

