name: "Weekly"
on:
  push:
    branches: [ 'weekly-test-builds' ]
jobs:
  macos:
    uses: ./.github/workflows/_build-macos.yml
  windows:
    uses: ./.github/workflows/_build-windows.yml
  windows-msvc:
    uses: ./.github/workflows/_build-windows-msvs.yml
