name: "Build on scripts"
on:
  pull_request:
    branches: [ 'master' ]
    types: ['opened', 'reopened', 'synchronize']
    paths-ignore:
      - 'msvc*/**'
      - 'check/**'
      - 'doc/**'
      - 'packaging/**'
      - 'snap/**'
      - '*.md'
      - 'check/**'
      - 'test-scripting/data/**'
      - 'test-scripting/python/**'
      - 'test-scripting/shaders/**'
      - 'test-scripting/scripting/focs/**'
      - 'test-scripting/stringtables/**'
      - '.github/ISSUE_TEMPLATE/**'
      - "pyproject.toml"
      - ".pre-commit-config.yaml"
jobs:
  windows:
    uses: ./.github/workflows/_build-windows.yml
