# Format description: https://github.com/Cjkjvfnby/run_only_needed_actions/#config-file-format
[workflow]
build_windows_with_cmake = ['focs_py', 'cpp', 'cmake', 'godot', 'workflows', 'focs_txt']
build_windows_with_msvs = ['cpp', 'workflows', 'visual_studio']
build_android = ['cpp', 'workflows']
build_macos = ['cpp', 'workflows']
build_ubuntu = ['cpp', 'workflows']
lint_py_focs = ['focs_py', 'pyproject_toml', 'python_dev_requirements', 'workflows']
lint_python = ['focs_py', 'pyproject_toml', 'python_dev_requirements', 'workflows', 'python']
lint_string_tables = ['stringtables', 'workflows']
lint_codeql = ['cpp', 'workflows']
noop = ['ignored']

[group.focs_py]
examples = ['default/scripting/species/sp_banforo.focs.py', 'default/scripting/focs/_species.pyi']
patterns = ['^(default/scripting|test-scripting).*\.pyi?$']

[group.focs_txt]
examples = [
    'default/scripting/species/common/shields.macros',
    'default/scripting/techs/techs.macros',
    'default/scripting/species/SP_SLY.focs.txt',
]
patterns = ['^(default/scripting|test-scripting)/.*\.(focs.txt|macros|macros.txt)$']

[group.pyproject_toml]
examples = ['pyproject.toml']
patterns = ['^pyproject.toml$']

[group.python_dev_requirements]
examples = ['default/python/requirements-dev.txt']
patterns = ['^default/python/requirements-dev.txt$']

[group.cpp]
examples = [
    'parse/CommonParamsParser.cpp',
    'parse/ConditionParser.h',
]
patterns = ['\.(cpp|h)']

[group.cmake]
examples = [
    'cmake/FreeOrionVersion.cmake.in',
    'cmake/FFindVorbis.cmake',
    'parse/CMakeLists.txt',
    'GG/cmake/GiGi.pc.in',
]
patterns = ['cmake']

[group.workflows]
examples = [
    '.github/workflows/project-labeler.yml',
]
patterns = ['^.github/workflows/']


[group.visual_studio]
examples = ['msvc2022/FreeOrion.sln']
patterns = ['^msvc2022/']

[group.python]
examples = [
    'check/st-tool.py',
    'default/python/AI/freeOrionAIInterface.pyi',
    'default/python/common/option_tools.py',
]
patterns = ['.pyi?$']

[group.stringtables]
examples = ['check/st-tool.py', 'default/stringtables/en.txt']
patterns = ['^default/stringtables', '^check/st-tool.py$']

[group.godot]
examples = ['godot/FleetWindow.gd']
patterns = ['^godot/.*.\.gd$']

[group.ignored]
examples = [
    'godot/assets/image/WindowFramePinWidgetOFF.png',
    'packaging/windows_installer.nsi.in',
    'doc/Doxyfile.in',
    'util/Serialize.ipp',
    'default/data/art/stars/old_stars/purple4.png',
    'default/scripting/techs/growth/GENOME_BANK.disabled',
    'default/scripting/starting_unlocks/buildings.inf',
]
patterns = [
    '^check/check_file_changed/config.toml$',
    '^.github/ISSUE_TEMPLATE/',
    '^\.github/CODEOWNERS$',
    '^\.github/id_ed25519.gpg',
    '^\.github/id_ed25519.pub',
    '^\.github/pre-deploy.sh',
    '^\.github/project-labels.yml',
    '^\.github/snap-xvfb-launch.sh',
    '^GG/doc/',
    '^GG/INSTALLING$',
    '^GG/PACKAGING$',
    '^GG/README$',
    '^GG/src/nanovg/nanovg.*\.c$',
    '^default/data/',
    '^default/python/charting/',
    '^default/python/handlers',
    '^default/shaders/',
    '^doc/',
    '^packaging',
    '^util',
    '^default/scripting/_readme_images',
    '^godot',
    '.gitattributes$',
    '\.gitignore$',
    '\.md$',
    'COPYING$',
    'LICENSE.txt$',
    'ai_debug_config.ini$',
    'client/human/FreeOrion.icns$',
    'client/human/FreeOrion.ico$',
    'client/human/FreeOrion.rc$',
    'client/human/GUIController.mm$',
    'client/human/chmain.mm$',
    'client/human/main.xib$',
    'credits.xml$',
    'default/scripting/empire_colors.xml$',
    'pre-commit-config.yaml$',
    'pytest.ini$',
    'snap/snapcraft.yaml$',
    'default/scripting/.*\.(inf|disabled)'
]
