name: "Snapcraft build"

on:
  push:
    paths-ignore:
      - 'msvc*/**'
      - 'check/**'
      - 'doc/**'
      - 'packaging/**'
      - '*.md'
      - 'check/**'
      - 'default/**'
      - 'test-scripting/**'
  pull_request:
    paths-ignore:
      - 'msvc*/**'
      - 'check/**'
      - 'doc/**'
      - 'packaging/**'
      - '*.md'
      - 'check/**'
      - 'default/**'
      - 'test-scripting/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build snap package
      uses: snapcore/action-build@v1
      id: snapcraft
    - name: Install built snap package
      run: |
        sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
    - name: Install dependencies for test launch
      run: |
        sudo apt install -y mesa-utils libgl1-mesa-dri libglx-mesa0
    - name: Test freeorion launch
      uses: GabrielBB/xvfb-action@v1.5
      with:
        run: /bin/bash .github/snap-xvfb-launch.sh

